/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Accorpamento } from './accorpamento';
import { LavAnagraficaOld } from './lavAnagraficaOld';
import { Operatore } from './operatore';

export interface AccorpTransazione { 
    codUserAggiorn?: string;
    codUserInserim?: Operatore;
    dataAggiorn?: Date;
    dataInserim?: Date;
    idSilAccorpTransazione?: number;
    idSilPrimario?: number;
    idSilSecondario?: LavAnagraficaOld;
    idSilTAccorpamento?: Accorpamento;
    timestamp?: number;
}