/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallInfo } from './callInfo';
import { ChiamataConferimDid } from './chiamataConferimDid';
import { LavSapDid } from './lavSapDid';
import { PoliticaA02 } from './politicaA02';
import { StatoEventoSez6 } from './statoEventoSez6';
import { StatoOccupazionale } from './statoOccupazionale';

export interface AllineaDidRequest { 
    callInfo?: CallInfo;
    chiamataConferimDid?: ChiamataConferimDid;
    dataInizioSospensione?: Date;
    idSilLavSapDid?: number;
    idSilLavSapSez6?: number;
    lavSapDid?: LavSapDid;
    listPoliticaA02?: Array<PoliticaA02>;
    listStatoOccupazionale?: Array<StatoOccupazionale>;
    reddito?: number;
    soloMessaggioOperazione?: boolean;
    sovrareddito?: string;
    statoEventoSez6?: StatoEventoSez6;
    tipoSovrareddito?: string;
    tipologiaAllineamento?: string;
}