/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Fontedato } from './fontedato';

export interface Ateco02 { 
    codSilTAteco02?: string;
    codTipoAteco?: string;
    dataFine?: Date;
    dataInizio?: Date;
    descrSilTAteco02?: string;
    fontedato?: Fontedato;
    idAteco91?: string;
    idSilTAteco02?: string;
    idSilTAtecoSuccessiva?: string;
}