/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ampiezza } from './ampiezza';
import { Ateco } from './ateco';
import { ComuneBlp } from './comuneBlp';
import { CpiBlp } from './cpiBlp';
import { NazioneBlp } from './nazioneBlp';

export interface AziAnagraficaBlp { 
    cap?: string;
    cfAzienda?: string;
    codPartitaIva?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    denominazione: string;
    denominazioneVisibile?: string;
    email: string;
    flgPubblicazDenominazione?: string;
    flgPubblicazIndirizzoWeb?: string;
    flgPubblicazNumFax?: string;
    flgPubblicazNumTelefono?: string;
    id?: number;
    idAmpiezza?: Ampiezza;
    idAteco?: Ateco;
    idComune?: ComuneBlp;
    idCpiCompetenza?: CpiBlp;
    idNazione?: NazioneBlp;
    idSilAziSede?: number;
    indirizzo?: string;
    indirizzoWeb?: string;
    note?: string;
    numFax?: string;
    numTelefono?: string;
}