/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ateco02 } from './ateco02';
import { Ccnl } from './ccnl';
import { NaturaGiuridica } from './naturaGiuridica';
import { Nazione } from './nazione';
import { TipoAzienda } from './tipoAzienda';

export interface AziAnagrafica { 
    ccnl?: Ccnl;
    codFiscale?: string;
    codMcDebole?: string;
    codMcForte?: string;
    codPartitaIva?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dataMcAggiornDebole?: Date;
    dataMcAggiornForte?: Date;
    descAltreInformazioni?: string;
    descAnilt?: string;
    descrDenominazione?: string;
    flgArtigiana?: string;
    flgAziEstera?: string;
    flgMaster?: string;
    flgPubblAmmin?: string;
    flgValiditaCf?: string;
    flgValiditaPiva?: string;
    idSilAziAnagrafica?: number;
    nazione?: Nazione;
    pec?: string;
    silTAteco02?: Ateco02;
    silTNaturaGiuridica?: NaturaGiuridica;
    silTTipoAzienda?: TipoAzienda;
    situazione?: string;
    timestamp?: number;
}