/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ateco02 } from './ateco02';
import { AziAnagrafica } from './aziAnagrafica';
import { AziReferente } from './aziReferente';
import { AziSedeIntermed } from './aziSedeIntermed';
import { Comune } from './comune';
import { Cpi } from './cpi';
import { Fontedato } from './fontedato';
import { Nazione } from './nazione';
import { Sede } from './sede';
import { StatoAzienda } from './statoAzienda';
import { Toponimo } from './toponimo';

export interface AziSede { 
    aziAnagrafica?: AziAnagrafica;
    codCap?: string;
    codInps?: string;
    codMcDebole?: string;
    codMcForte?: string;
    codPatInail?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    comune?: Comune;
    dataAggiorn?: Date;
    dataFineAttivita?: Date;
    dataInizioAttivita?: Date;
    dataInserim?: Date;
    dataMcAggiornDebole?: Date;
    dataMcAggiornForte?: Date;
    dataNumDipendenti?: Date;
    descrDenominazione?: string;
    descrFax?: string;
    descrIndirizzo?: string;
    descrLocalita?: string;
    descrMotivo?: string;
    descrNote?: string;
    descrNumCivico?: string;
    descrNumDipendenti?: string;
    descrTelefono?: string;
    email?: string;
    flgLuogo?: string;
    flgObblProsDisabili?: string;
    flgValida?: string;
    fontedato?: Fontedato;
    idSilAziSede?: number;
    idSilTClasseAmpiezza?: string;
    intermediari?: Array<AziSedeIntermed>;
    nazione?: Nazione;
    numAgSomm?: string;
    numArchivio?: number;
    numPreferenza?: number;
    referenti?: Array<AziReferente>;
    silTAteco02?: Ateco02;
    silTCpi?: Cpi;
    silTSede?: Sede;
    silTStatoAzienda?: StatoAzienda;
    timestamp?: number;
    toponimo?: Toponimo;
}