/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ComuneBlp } from './comuneBlp';
import { NazioneBlp } from './nazioneBlp';

export interface BlpLavAnagrafica { 
    capDom?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    codiceFiscale: string;
    codiceFiscaleEstero?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    dNascita: Date;
    dsCognome: string;
    dsIndirizzoDom?: string;
    dsNome: string;
    eMail: string;
    genere: string;
    id?: number;
    idComuneDomicilio?: ComuneBlp;
    idNazioneDomicilio?: NazioneBlp;
    idSilLavAnagrafica: number;
    note?: string;
    numCellulare?: string;
    numTelefono?: string;
}