/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbilitazionePossedutaCv } from './abilitazionePossedutaCv';
import { AlboCV } from './alboCV';
import { BlpLavAnagraficaCv } from './blpLavAnagraficaCv';
import { Decodifica } from './decodifica';
import { EsperienzaLavCv } from './esperienzaLavCv';
import { FonteCv } from './fonteCv';
import { FormazioneCv } from './formazioneCv';
import { InformaticaDichCv } from './informaticaDichCv';
import { Intermediario } from './intermediario';
import { IstruzioneDichCv } from './istruzioneDichCv';
import { LinguaDichCv } from './linguaDichCv';
import { ListaSpecialeCv } from './listaSpecialeCv';
import { Operatore } from './operatore';
import { PatentePossedutaCv } from './patentePossedutaCv';
import { ProfessioneDesiderataCv } from './professioneDesiderataCv';

export interface CandidaturaCv { 
    abilitazionePossedutaList?: Array<AbilitazionePossedutaCv>;
    codCandidatura?: string;
    codStatoCandidatura?: Decodifica;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    dInvio?: Date;
    dScadenza?: Date;
    emailInvio?: string;
    esperienzaLavList?: Array<EsperienzaLavCv>;
    flgGeneratoDaSistema?: string;
    flgL68?: string;
    flgMezzoProprio?: string;
    flgStampaL68?: string;
    flgTrasferte?: string;
    flgVisibilitaIntermediario?: string;
    formazioneList?: Array<FormazioneCv>;
    id?: number;
    idAmbitoDiffusione?: number;
    idFonteCandidatura?: FonteCv;
    idIntermediario?: Intermediario;
    idLavAnagrafica?: BlpLavAnagraficaCv;
    idListaSpeciale?: ListaSpecialeCv;
    idSilLavAnagrafica?: number;
    idTipoComunicazione?: number;
    incentiviEQualita?: string;
    informaticaDichList?: Array<InformaticaDichCv>;
    iscrizioneAlboDichList?: Array<AlboCV>;
    linguaDichList?: Array<LinguaDichCv>;
    paroleChiaveMatching?: string;
    patentePossedutaList?: Array<PatentePossedutaCv>;
    professioneDesiderataList?: Array<ProfessioneDesiderataCv>;
    silOperatoreInserim?: Operatore;
    titoloCv?: string;
    titoloStudioList?: Array<IstruzioneDichCv>;
    ulterioriInformazioni?: string;
}