/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AltroCorso } from './altroCorso';
import { ConoscenzaInformatica } from './conoscenzaInformatica';
import { Decodifica } from './decodifica';
import { ElencoPropensioni } from './elencoPropensioni';
import { EsperienzaProfessionale } from './esperienzaProfessionale';
import { FormazioneProfessionalePiemontese } from './formazioneProfessionalePiemontese';
import { LavTitoloStudio } from './lavTitoloStudio';
import { LavTitoloStudioAltro } from './lavTitoloStudioAltro';
import { LinguaStraniera } from './linguaStraniera';

export interface CandidaturaSilp { 
    abilitazionePossedutaList?: Array<Decodifica>;
    altroCorsoList?: Array<AltroCorso>;
    codCandidatura?: string;
    codStatoCandidatura?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    dInvio?: Date;
    dScadenza?: Date;
    emailInvio?: string;
    esperienzaLavList?: Array<EsperienzaProfessionale>;
    flgGeneratoDaSistema?: string;
    flgL68?: string;
    flgStampaL68?: string;
    flgVisibilitaIntermediario?: string;
    formazioneList?: Array<FormazioneProfessionalePiemontese>;
    id?: number;
    idAmbitoDiffusione?: number;
    idFonteCandidatura?: number;
    idIntermediario?: number;
    idListaSpeciale?: number;
    idSilLavAnagrafica?: number;
    idTipoComunicazione?: number;
    incentiviEQualita?: string;
    informaticaDichList?: Array<ConoscenzaInformatica>;
    iscrizioneAlboDichList?: Array<Decodifica>;
    linguaDichList?: Array<LinguaStraniera>;
    paroleChiaveMatching?: string;
    patentePossedutaList?: Array<Decodifica>;
    professioneDesiderataList?: Array<ElencoPropensioni>;
    titoloCv?: string;
    titoloStudioAltroList?: Array<LavTitoloStudioAltro>;
    titoloStudioList?: Array<LavTitoloStudio>;
    ulterioriInformazioni?: string;
}