/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TipoCheck } from './tipoCheck';

export interface CheckControl { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    flgCobScartBlocc?: string;
    flgDidConferitaAllinN00?: string;
    flgDidPres?: string;
    flgDidStInserConfer?: string;
    flgDomicPiemonte?: string;
    flgN00Pres?: string;
    flgPresMailCell?: string;
    flgRdlAperti?: string;
    idSilwebTCheckControl?: number;
    silwebDTipoCheck?: TipoCheck;
    timestamp?: number;
}