/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TipoCheck } from './tipoCheck';

export interface CheckAutocer { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dDid?: Date;
    dInserim?: Date;
    dsNote?: string;
    flgDidAutonomo?: string;
    flgDidDipendente?: string;
    flgDidElemIstrutt?: string;
    flgDidImmDisponib?: string;
    flgDidNoLavora?: string;
    flgDidRevoca?: string;
    flgDidSospesa?: string;
    idSilLavSapDid?: number;
    idSilwebTCheckAutocer?: number;
    silwebDTipoCheck?: TipoCheck;
    timestamp?: number;
}