/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LavDatiConferimDid } from './lavDatiConferimDid';
import { LavSapDid } from './lavSapDid';
import { ProfilingQuant } from './profilingQuant';
import { StatoOccupMin } from './statoOccupMin';

export interface ChiamataConferimDid { 
    codEntePromotore?: string;
    codEsito?: string;
    codEsitoMin?: string;
    codStatoDid?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataAnzianita?: Date;
    dataEvento?: Date;
    dataInserim?: Date;
    descrEsito?: string;
    dsMotivoConferimento?: string;
    dsNote?: string;
    flgProseguitoSuErr?: string;
    flgRitrasmetti?: string;
    idSilChiamataConferimDid?: number;
    idSilInterscambioInvio?: number;
    idSilTClasseOccupMin?: string;
    indiceProfiling?: number;
    mesiAnzianita?: number;
    numRisottomissioni?: number;
    silLavDatiConferimDid?: LavDatiConferimDid;
    silLavSapDid?: LavSapDid;
    silProfilingQuant?: ProfilingQuant;
    silTStatoOccupMin?: StatoOccupMin;
}