/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cpi } from './cpi';
import { Fontedato } from './fontedato';

export interface ChiamataProfQuant { 
    codEnteIntermediario?: string;
    codEsito?: string;
    codTipoChiamataProfiling?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    codiceFiscaleLavoratore?: string;
    dataAggiorn?: Date;
    dataChiamata?: Date;
    dataInserim?: Date;
    dsEsito?: string;
    idSilChiamataProfQuant?: number;
    idSilLavDatiConferimDid?: number;
    idSilPjSedeSocieta?: number;
    idSilPjSocieta?: number;
    silTCpi?: Cpi;
    silTFontedato?: Fontedato;
}