/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CpiBlp } from './cpiBlp';

export interface CollaboratoreIntermediario { 
    codUserAggiorn: string;
    codUserInserim: string;
    cognome?: string;
    dAggiorn: Date;
    dFine?: Date;
    dInizio: Date;
    dInserim: Date;
    flgResponsabile?: string;
    idCollaboratoreIntermediario: number;
    idCpiOpeartore: CpiBlp;
    idIntermediario: number;
    idOperatore: string;
    nome?: string;
}