/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comunicazione } from './comunicazione';
import { Cpi } from './cpi';
import { Fontedato } from './fontedato';
import { Tracciato } from './tracciato';

export interface ComunicazioneDto { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAnnulloComunicazione?: Date;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dsMotivoAnnullamento?: string;
    dsNote?: string;
    flgClassificato?: string;
    flgConforme?: string;
    flgStato?: string;
    idSilClassificazione?: number;
    idSilCodiceComunicazione?: string;
    idSilComunicazione?: number;
    idSilTComMotivoInserim?: number;
    idSilTComSoggComunicante?: string;
    silTComunicazione?: Comunicazione;
    silTCpi?: Cpi;
    silTFontedato?: Fontedato;
    silTTuTracciato?: Tracciato;
    timestamp?: number;
}