/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProvinciaBlp } from './provinciaBlp';

export interface ComuneBlp { 
    codCap?: string;
    codInps?: string;
    codIstat?: string;
    codPrefisso?: string;
    dFine?: Date;
    dInizio?: Date;
    dsComune?: string;
    idComune?: string;
    idCpi?: number;
    idProvincia?: ProvinciaBlp;
    latitudine?: number;
    longitudine?: number;
}