/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ComunicazioneObbligatoria { 
    capSedeLavoroAgenziaSomministrazione?: string;
    capSedeLavoroDatore?: string;
    capSedeLavoroDittaUtilizzatrice?: string;
    cittadinanzaLavoratore?: string;
    codiceAgevolazioneRapporto?: string;
    codiceAgevolazioniRapportoDittaUtilizzatrice?: string;
    codiceCCNLRapporto?: string;
    codiceCCNLRapportoDittaUtilizzatrice?: string;
    codiceCausaCessazioneRapporto?: string;
    codiceComunicazione?: string;
    codiceComunicazionePrecedente?: string;
    codiceEntePrevidenzialeRapporto?: string;
    codiceEntePrevidenzialeRapportoAgenziaSomm?: string;
    codiceFiscaleAgenziaSomministrazione?: string;
    codiceFiscaleDatore?: string;
    codiceFiscaleDatoreDistaccatario?: string;
    codiceFiscaleDittaUtilizzatrice?: string;
    codiceFiscaleLavoratore?: string;
    codiceFiscaleLavoratoreCoobbligato?: string;
    codiceSettoreAtecoDatore?: string;
    codiceTrasformazioneRapporto?: string;
    codiceTrasformazioneRapportoDittaUtilizzatrice?: string;
    cognomeLavoratore?: string;
    comuneNascitaLavoratore?: string;
    comuneNazioneNascitaLavoratore?: string;
    comuneNazioneSedeLavoroAgenziaSomministrazione?: string;
    comuneNazioneSedeLavoroDatore?: string;
    comuneNazioneSedeLavoroDittaUtilizzatrice?: string;
    comuneSedeLavoroDatore?: string;
    comunicazioneCessazione?: boolean;
    comunicazioneUnilav?: boolean;
    comunicazioneUnimare?: boolean;
    comunicazioneUnisomm?: boolean;
    comunicazioneUniurg?: boolean;
    comunicazioneVardatori?: boolean;
    dataCessazioneRapporto?: Date;
    dataCessazioneRapportoAgenziaSomm?: Date;
    dataCessazioneRapportoDittaUtilizzatrice?: Date;
    dataFineMissioneRapportoDittaUtilizzatrice?: Date;
    dataFineProrogaRapporto?: Date;
    dataFineProrogaRapportoAgenziaSomm?: Date;
    dataFineProrogaRapportoDittaUtilizzatrice?: Date;
    dataFineRapporto?: Date;
    dataFineRapportoAgenziaSomm?: Date;
    dataInizioMissioneRapportoDittaUtilizzatrice?: Date;
    dataInizioRapporto?: Date;
    dataInizioRapportoAgenziaSomm?: Date;
    dataNascitaLavoratore?: Date;
    dataRicezioneModulo?: Date;
    dataRiferimento?: Date;
    dataTrasformazioneRapporto?: Date;
    dataTrasformazioneRapportoDittaUtilizzatrice?: Date;
    denominazioneAgenziaSomministrazione?: string;
    denominazioneDatore?: string;
    denominazioneDittaUtilizzatrice?: string;
    descrizioneAgevolazioneRapporto?: string;
    descrizioneAgevolazioniRapportoDittaUtilizzatrice?: string;
    descrizioneCCNLRapporto?: string;
    descrizioneCCNLRapportoDittaUtilizzatrice?: string;
    descrizioneCategoriaIscrizioneLavoratore?: string;
    descrizioneCausaCessazioneRapporto?: string;
    descrizioneCittadinanzaLavoratore?: string;
    descrizioneComuneNazioneNascitaLavoratore?: string;
    descrizioneComuneNazioneSedeLavoroAgenziaSomministrazione?: string;
    descrizioneComuneNazioneSedeLavoroDatore?: string;
    descrizioneComuneNazioneSedeLavoroDittaUtilizzatrice?: string;
    descrizioneComuneNazioneSedeLavoroTerraComandataDatore?: string;
    descrizioneEntePrevidenzialeRapporto?: string;
    descrizioneEntePrevidenzialeRapportoAgenziaSomm?: string;
    descrizioneLuogoImmatricolazioneMatricolaLavoratore?: string;
    descrizioneLuogoIscrizioneNaveSedeLavoroDatore?: string;
    descrizioneSettoreAtecoDatore?: string;
    descrizioneSettoreAtecoDatoreLavoroPrecedente?: string;
    descrizioneSettoreAtecoSedeLavoroDittaUtilizzatrice?: string;
    descrizioneTipoNaveSedeLavoroDatore?: string;
    descrizioneTipoOrarioRapporto?: string;
    descrizioneTipoOrarioRapportoDittaUtilizzatrice?: string;
    descrizioneTipologiaContrattualeRapporto?: string;
    descrizioneTipologiaContrattualeRapportoAgenziaSomm?: string;
    descrizioneTrasferimentoAzienda?: string;
    descrizioneTrasformazioneRapporto?: string;
    descrizioneTrasformazioneRapportoDittaUtilizzatrice?: string;
    flgAssunzioneForzaMaggiore?: string;
    flgLavoroInAgricolturaRapporto?: string;
    flgLavoroInAgricolturaRapportoDittaUtilizzatrice?: string;
    flgPubblicaAmministrazioneDatore?: string;
    flgPubblicaAmministrazioneDittaUtilizzatrice?: string;
    flgSocioLavoratore?: string;
    indennitaDisponibilitaRapportoAgenziaSomm?: string;
    indirizzoSedeLavoroAgenziaSomministrazione?: string;
    indirizzoSedeLavoroDatore?: string;
    indirizzoSedeLavoroDittaUtilizzatrice?: string;
    nazioneNascitaLavoratore?: string;
    nazioneSedeLavoroDatore?: string;
    nomeLavoratore?: string;
    numeroAgenziaSomministrazioneRapportoAgenziaSomm?: string;
    numeroContrattoSomministrazione?: string;
    numeroMatricolaRapportoAgenziaSomm?: string;
    oreSettimanaliMedieRapporto?: string;
    oreSettimanaliRapportoDittaUtilizzatrice?: string;
    sessoLavoratore?: string;
    settoreAtecoSedeLavoroDittaUtilizzatrice?: string;
    tipoModulo?: string;
    tipoOrarioRapporto?: string;
    tipoOrarioRapportoDittaUtilizzatrice?: string;
    tipoTracciatoFromTipoModulo?: string;
    tipologiaContrattualeRapporto?: string;
    tipologiaContrattualeRapportoAgenziaSomm?: string;
}