/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';

export interface CondizioneLavorativaOfferta { 
    ccnl?: Decodifica;
    comuneSedeLavoro?: Decodifica;
    durataContratto?: number;
    gradoContrattuale?: Decodifica;
    id?: number;
    intervalloRetribuzione?: Decodifica;
    modalitaLavoro?: Decodifica;
    nazioneSedeLavoro?: Decodifica;
    provinciaSedeLavoro?: Decodifica;
    tipoRapportoLavoro?: Decodifica;
    ulterioriCondizioniOfferte?: string;
}