/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CcnlBlp } from './ccnlBlp';
import { ComuneBlp } from './comuneBlp';
import { GradoContrattuale } from './gradoContrattuale';
import { IntervalloRalBlp } from './intervalloRalBlp';
import { ModalitaLavoroBlp } from './modalitaLavoroBlp';
import { NazioneBlp } from './nazioneBlp';
import { TipoRapportoLavoro } from './tipoRapportoLavoro';

export interface CondLavorativaOfferta { 
    blpTVacancy: number;
    codUserAggiorn: string;
    codUserInserim: string;
    dAggiorn: Date;
    dInserim: Date;
    durataContratto?: number;
    id?: number;
    idCcnl?: CcnlBlp;
    idComuneSedeLavoro?: ComuneBlp;
    idGradoContrattuale?: GradoContrattuale;
    idIntervalloRal?: IntervalloRalBlp;
    idModalitaLavoro?: ModalitaLavoroBlp;
    idNazioneSedeLavoro?: NazioneBlp;
    idTipoRapportoLavoro: TipoRapportoLavoro;
    ulterioriCondizioniOfferte?: string;
}