/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ConsultaAnnunciRidotto { 
    azienda?: string;
    cfAzienda?: string;
    contratto?: string;
    dataScadenza?: Date;
    dataStato?: Date;
    descrComuneSede?: string;
    descrCpi?: string;
    descrNazioneSede?: string;
    descrProvinciaSede?: string;
    dsIntermediario?: string;
    dsProfiloIstat?: string;
    flgL68Art1?: string;
    flgL68Art18?: string;
    idAnnuncio?: number;
    idIntermediario?: number;
    idProfiloIstat?: string;
    idSilAziSede?: number;
    idStatoVacancy?: number;
    mapsUrls?: string;
    numAnnuncio?: string;
    qualifica?: string;
    servizioSpecialistico?: string;
    stato?: string;
    titoloVacancy?: string;
}