/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallInfo } from './callInfo';
import { SchedaAnagraficaProfessionale } from './schedaAnagraficaProfessionale';

export interface ControlliFascicoloRequest { 
    callInfo?: CallInfo;
    coordTabAttivo?: string;
    coordTabDestino?: string;
    flgFattaDomandaSalva?: boolean;
    idSilLavAnagrafica?: string;
    schedaModificata?: SchedaAnagraficaProfessionale;
    schedaOriginale?: SchedaAnagraficaProfessionale;
    sezioniSapModificate?: Array<string>;
    tipoOperazione?: string;
}