/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AltriCorsiCV } from './altriCorsiCV';
import { Decodifica } from './decodifica';
import { LavAnagraficaAlbi } from './lavAnagraficaAlbi';
import { LavInformatica } from './lavInformatica';
import { LavLingua } from './lavLingua';
import { LinguaStraniera } from './linguaStraniera';
import { TitoliStudioCV } from './titoliStudioCV';

export interface CurriculumVitae { 
    albi?: Array<LavAnagraficaAlbi>;
    altriCorsi?: Array<AltriCorsiCV>;
    codCandidatura?: string;
    codStatoCandidatura?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    conoscenzeInformatiche?: Array<LavInformatica>;
    dAggiorn?: Date;
    dInserim?: Date;
    dInvio?: Date;
    dScadenza?: Date;
    emailInvio?: string;
    flgGeneratoDaSistema?: string;
    flgL68?: string;
    flgStampaL68?: string;
    flgVisibilitaIntermediario?: string;
    idAmbitoDiffusione?: number;
    idCVBlp?: number;
    idFonteCandidatura?: number;
    idIntermediario?: number;
    idListaSpeciale?: number;
    idSilLavAnagrafica?: number;
    idTipoComunicazione?: number;
    incentiviEQualita?: string;
    linguaDichList?: Array<LinguaStraniera>;
    lingueStraniere?: Array<LavLingua>;
    paroleChiaveMatching?: string;
    patenti?: Array<Decodifica>;
    patentini?: Array<Decodifica>;
    titoliDiStudio?: Array<TitoliStudioCV>;
    titoloCv?: string;
    ulterioriInformazioni?: string;
}