/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cittadinanza } from './cittadinanza';
import { Decodifica } from './decodifica';
import { FonteAggiornamento } from './fonteAggiornamento';
import { Luogo } from './luogo';

export interface DatiPersonali { 
    cittadinanza?: Cittadinanza;
    codiceFiscale?: string;
    cognome?: string;
    dataDiNascita?: Date;
    flgArchiviato?: string;
    fonteAggiornamento?: FonteAggiornamento;
    genere?: Decodifica;
    luogoDiNascita?: Luogo;
    nome?: string;
    statoCivile?: Decodifica;
}