/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallInfo } from './callInfo';

export interface DatiTitoloStudioLavoratore { 
    callInfo?: CallInfo;
    codFiscaleLav?: string;
    dsAnnoCompletato?: string;
    dsCognomeLav?: string;
    dsNomeLav?: string;
    dsTitoloStudioSap?: string;
    dsVoto?: string;
    flgCompletato?: string;
    flgCumLaude?: string;
    flgPubblicazione?: string;
    flgRiconosciutoItalia?: string;
    idSilLav?: number;
    idSilTStudio?: string;
}