/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DatiAnnuncio { 
    cfAzienda?: string;
    comuneSedeAnnuncio?: string;
    denominazioneAzienda?: string;
    idManifestazione?: number;
    idSilAziSede?: number;
    nazioneSedeAnnuncio?: string;
    nomeManifestazione?: string;
    numeroAnnuncio?: string;
    provinciaSedeAnnuncio?: string;
    pubblicatoDa?: string;
    qualificaIstat?: string;
    statoAnnuncio?: string;
    titoloAnnuncio?: string;
}