/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ateco02 } from './ateco02';
import { Comune } from './comune';
import { Nazione } from './nazione';

export interface DatoreLavoroDTO { 
    capSedeLavoro?: string;
    capSedeLegale?: string;
    codFiscale?: string;
    dsDenominazione?: string;
    dsIndirizzoSedeLavoro?: string;
    dsIndirizzoSedeLegale?: string;
    emailSedeLavoro?: string;
    emailSedeLegale?: string;
    faxSedeLavoro?: string;
    faxSedeLegale?: string;
    flgAziEstera?: string;
    flgPubblAmmin?: string;
    idSilAziSedeDestVdt?: number;
    idSilTTuTipoDatoreLavoro?: number;
    idSilTuDatoreLavoro?: number;
    idSilTuImportComunicazione?: number;
    numIscrAlboSomministrazione?: string;
    silTAteco02?: Ateco02;
    silTComSedeLav?: Comune;
    silTComSedeLeg?: Comune;
    silTNazSedeLav?: Nazione;
    silTNazSedeLeg?: Nazione;
    stringaVariazioneVdt?: string;
    telefonoSedeLavoro?: string;
    telefonoSedeLegale?: string;
    uddlDsCognome?: string;
    uddlDsNome?: string;
}