/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TipoResponsabilita } from './tipoResponsabilita';
import { Utente } from './utente';

export interface Delega { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dFine?: Date;
    dInizio?: Date;
    dInserim?: Date;
    idDelega?: number;
    numCellulare?: string;
    pslpDTipoResponsabilita?: TipoResponsabilita;
    pslpTUtente1?: Utente;
    pslpTUtente2?: Utente;
}