/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallInfo } from './callInfo';

export interface DettaglioEsitoInvio { 
    callInfo?: CallInfo;
    codice?: DettaglioEsitoInvio.CodiceEnum;
    descrizione?: string;
}
export namespace DettaglioEsitoInvio {
    export type CodiceEnum = 'OK' | 'KO' | 'EL';
    export const CodiceEnum = {
        OK: 'OK' as CodiceEnum,
        KO: 'KO' as CodiceEnum,
        EL: 'EL' as CodiceEnum
    };
}