/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DettaglioComunicazioneObbligatoria { 
    anniEsperTutor?: number;
    cfSoggPromotore?: string;
    codComunicazioneRegio?: string;
    codComunicazioneRegioPrec?: string;
    codFiscaleTutor?: string;
    codTpContratto?: string;
    cognomeTutor?: string;
    cpiSoggPromotore?: string;
    dataCessazMissione?: Date;
    dataComunicazione?: Date;
    dataFineMissione?: Date;
    dataFinePeriodoFormativo?: Date;
    dataFineProroga?: Date;
    dataInizio?: Date;
    dataInizioMissione?: Date;
    dataNascitaTutor?: Date;
    dataProrogaMissione?: Date;
    dataRientroDistacco?: Date;
    dataTrasfMissione?: Date;
    dataVisitaMedicaTutor?: Date;
    descCategLavorat?: string;
    descCausaCessAziUtil?: string;
    descCcnl?: string;
    descEntePrevidenziale?: string;
    descGradoTutor?: string;
    descLivello?: string;
    descMissione?: string;
    descNaturaGiuridicaAzi?: string;
    descOrario?: string;
    descPatInail?: string;
    descQualifica?: string;
    descQualificaTutor?: string;
    descTpComunicazione?: string;
    dsCategTirocinante?: string;
    dsNormAssunzione?: string;
    dsSoggettoPromotore?: string;
    dsTipolTirocinio?: string;
    flArtigianoAzi?: string;
    flgAssunazL68?: string;
    flgAssunzioneObblig?: string;
    flgDistaccoEstero?: string;
    flgDistaccoParz?: string;
    flgForma?: string;
    flgGeneratoTirocinio?: string;
    flgLavAgricol?: string;
    flgLavInMobilita?: string;
    flgProsecuzDiFatto?: string;
    flgSocioLavoratore?: string;
    flgSomministraz?: string;
    flgSomministrazTempoDeterm?: string;
    flgStagionale?: string;
    flgTitolareTutor?: string;
    flgVisitaIspettiva?: string;
    idAziCoTrasf?: number;
    idCategLavorat?: string;
    idCausaCessAziUtil?: number;
    idCcnl?: string;
    idEntePrevidenziale?: number;
    idGradoTutor?: string;
    idNaturaGiuridicaAzi?: string;
    idOrario?: string;
    idQualifica?: string;
    idQualificaTutor?: string;
    idSilStoricoRapportoLavoro?: string;
    idSilTuDatiRapporto?: number;
    idSilTuDatoreLav?: number;
    idSilTuImportComRapCo?: number;
    idSilTuImportComRapCoVard?: number;
    idSilTuImportComunic?: number;
    l68DataAtto?: Date;
    l68NumAtto?: string;
    l68TpAtto?: string;
    livelloTutor?: string;
    nomeTutor?: string;
    numAgenziaSomministAzi?: number;
    numContrattoAziUtil?: number;
    numGGPrevisteAgric?: number;
    numIndennitaDisponib?: number;
    numOreSettMedie?: number;
    numOreSettMedieTrasform?: number;
    patInailDistacco?: string;
    retribuzLordaAnnua?: number;
    sessoTutor?: string;
    tipoContratto?: string;
    tipoLavorazione?: string;
    tipoPromotore?: string;
}