/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DidInpsRidotta { 
    cellLavoratore?: string;
    codStatoElaborazioneDid?: string;
    codiceFiscale?: string;
    cognome?: string;
    desStatoElaborazioneDid?: string;
    descrCpi?: string;
    dtConvocazione?: Date;
    dtDichiarazione?: Date;
    dtInvio?: Date;
    flgAnnullato?: string;
    idCpi?: number;
    idProvvedimento?: number;
    idSilInterscambio?: number;
    idSilLavAnagrafica?: number;
    idSilLavSapDid?: number;
    identificativoDid?: string;
    mail?: string;
    nome?: string;
    recapitiDid?: string;
}