/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DidRidotta { 
    codFiscale?: string;
    codStatoAnpal?: string;
    codStatoDid?: string;
    codiceEntePromotore?: string;
    cognome?: string;
    dataDid?: Date;
    dataInizioAnpal?: Date;
    dataProposta?: Date;
    dataStatoAnpal?: Date;
    dataStatoDid?: Date;
    descrEnteOperatSap?: string;
    descrEnteTitolareSap?: string;
    descrStatoAnpal?: string;
    flgAllineataAnpalSilp?: string;
    flgEventoFinale?: string;
    flgSottoReddito?: string;
    flgStatoDidFinale?: string;
    flgUltimaDid?: string;
    idCpiCompetenza?: number;
    idPresaInCarico?: string;
    idSilLavAnagrafica?: number;
    idSilLavSapDid?: number;
    idSilLavSapSez6?: number;
    idSilStatoEventoSez6?: number;
    idVista?: string;
    identificativoPolitica?: string;
    nome?: string;
    numeroRiga?: string;
    statoAnpal?: string;
    statoDid?: string;
    totReddProspettico?: string;
    tpStatoAnpal?: string;
}