/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiMessage } from './apiMessage';
import { ChiamataConferimDid } from './chiamataConferimDid';
import { LavSapDid } from './lavSapDid';
import { PoliticaA02 } from './politicaA02';
import { StatoEventoSez6 } from './statoEventoSez6';
import { StatoOccupazionale } from './statoOccupazionale';

export interface DidResponse { 
    allineamentoMessages?: Array<ApiMessage>;
    apiMessages?: Array<ApiMessage>;
    chiamataConferimDid?: ChiamataConferimDid;
    codiceSap?: string;
    dataInizioSospensione?: Date;
    esitoPositivo?: boolean;
    identificativoPoliticaN00?: string;
    isAllineatoN00Did?: boolean;
    isConferirePerAllineareN00Did?: boolean;
    isLavoratoreIscrittoComi?: boolean;
    isPattoServizioAperto?: boolean;
    lavSapDid?: LavSapDid;
    listPoliticaA02?: Array<PoliticaA02>;
    listStatoOccupazionaleByCo?: Array<StatoOccupazionale>;
    numComunicazioniScartate?: number;
    numGiorniDisoccupazioneCalcolati?: number;
    reddito?: number;
    sovrareddito?: string;
    statoEventoSez6?: StatoEventoSez6;
    tipoSovrareddito?: string;
}