/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Risposta } from './risposta';

export interface Domanda { 
    classNamePunteggio?: string;
    classNameValorizzazione?: string;
    codMinistero?: string;
    dsElencoIdRisposte?: string;
    dsSilwebTDomanda?: string;
    dtFine?: Date;
    dtInizio?: Date;
    flgHidden?: string;
    flgSolaLettura?: string;
    idSilwebTDomanda?: number;
    numMaxRisposte?: number;
    numMaxScelte?: number;
    numOrdine?: number;
    silwebTRispostas?: Array<Risposta>;
    silwebTSottoDomanda?: Domanda;
}