/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropensioniPreferenzeQualifica } from './propensioniPreferenzeQualifica';

export interface ElencoPropensioni { 
    cfLavoratore?: string;
    contattoBlp?: string;
    cvAutorizBL?: string;
    cvDataAggiorn?: Date;
    cvDataAutoriz?: Date;
    cvNote?: string;
    dispBassaProf?: string;
    dispForm?: string;
    dispTir?: string;
    email?: string;
    idLavoratore?: number;
    listaPropQualifiche?: Array<PropensioniPreferenzeQualifica>;
    utilizzoMP_Lav?: string;
    utilizzoMP_Rag_Lav?: string;
}