/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ComuneBlp } from './comuneBlp';
import { NazioneBlp } from './nazioneBlp';
import { QualificaBlp } from './qualificaBlp';
import { TipoRapportoLavoro } from './tipoRapportoLavoro';

export interface EsperienzaLav { 
    codUserAggiorn: string;
    codUserInserim: string;
    dAggiorn: Date;
    dFineRapporto?: Date;
    dInizioRapporto?: Date;
    dInserim: Date;
    dsDatoreLavoro?: string;
    dsIndirizzoDatoreLavoro?: string;
    dsMansioniResponsabil?: string;
    dsQualifica?: string;
    flgEsperienzaCo: string;
    flgLavoroAttuale: string;
    flgPubblicazioneDatoreLav?: string;
    id?: number;
    idCandidatura: number;
    idComuneDatoreLavoro?: ComuneBlp;
    idNazioneDatoreLavoro?: NazioneBlp;
    idQualifica?: QualificaBlp;
    idSilLAvEsperienzaLavoro?: number;
    idTipoRapportoLavoro: TipoRapportoLavoro;
}