/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PattoDiServizio } from './pattoDiServizio';

export interface FonteFinanzMin { 
    codFonteFinanzMin?: string;
    dataFine?: Date;
    dataInizio?: Date;
    descrFonteFinanzMin?: string;
    flgGol?: string;
    flgQualitativo?: string;
    idSilTFonteFinanzMin?: number;
    silPattoDiServizios?: Array<PattoDiServizio>;
}