/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderField } from './orderField';

export interface FormRicercaCurriculum { 
    codStatoCurriculum?: Array<string>;
    codiceFiscale?: string;
    cognome?: string;
    dataAggiornamentoA?: Date;
    dataAggiornamentoDa?: Date;
    dataScadenzaA?: Date;
    dataScadenzaDa?: Date;
    idSilLavAnagrafica?: number;
    nome?: string;
    ordinamento?: Array<OrderField>;
}