/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comune } from './comune';
import { Nazione } from './nazione';
import { Qualifica } from './qualifica';
import { TipologiaDurata } from './tipologiaDurata';
import { Toponimo } from './toponimo';

export interface FormazioneCv { 
    dFine?: Date;
    dInizio?: Date;
    denominazioneAziendaFormazione?: string;
    dsCorso?: string;
    dsQualificaAcquisita?: string;
    durata?: number;
    flgFormazionePiemontese?: string;
    flgInCorso?: string;
    flgPubblicazioneCorso?: string;
    flgTirocinioCurriculare?: string;
    id?: number;
    idCandidatura?: number;
    idComuneSedeCorso?: Comune;
    idNazioneSedeCorso?: Nazione;
    idQualificaAcquisita?: Qualifica;
    idSilLavCorsoForm?: number;
    idToponimoSedeCorso?: Toponimo;
    idUnitaMisuraDurata?: TipologiaDurata;
    indirizzoSedeCorso?: string;
    numCivicoSedeCorso?: string;
}