/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallInfo } from './callInfo';
import { OrderField } from './orderField';

export interface FormRicercaAutocertificazioni { 
    callInfo?: CallInfo;
    codiceFiscale?: string;
    cognome?: string;
    dataAutocertificazioneA?: Date;
    dataAutocertificazioneDa?: Date;
    idCpiOperatore?: number;
    idEntePromotore?: number;
    idOperatore?: string;
    idSilLavAnagrafica?: number;
    idTipoDocumentoRichiesto?: number;
    nome?: string;
    ordinamento?: OrderField;
}