/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderField } from './orderField';

export interface FormRicercaAnnunci { 
    cfAzienda?: string;
    codFiscaleSoggAbilitato?: string;
    dataStatoA?: Date;
    dataStatoDa?: Date;
    denominazioneAzienda?: string;
    denominazioneSoggAbilitato?: string;
    flgL68Art1?: string;
    flgL68Art18?: string;
    idAnnuncio?: number;
    idCpi?: number;
    idDomandaIscrizioneEspositore?: number;
    idIntermediario?: number;
    idManifestazione?: number;
    idOperatoreCruscotto?: string;
    idProfiloIstat?: string;
    idServizioSpecialistico?: number;
    idSilAziAnagrafica?: number;
    idStatoAnnuncio?: Array<number>;
    idTipoRapportoLavoro?: number;
    mansione?: string;
    ordinamento?: Array<OrderField>;
    qualifica?: string;
    titoloAnnuncio?: string;
}