/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attestazione } from './attestazione';
import { ComuneBlp } from './comuneBlp';
import { NazioneBlp } from './nazioneBlp';
import { QualificaBlp } from './qualificaBlp';
import { ToponimoBlp } from './toponimoBlp';
import { UnitaMisuraDurata } from './unitaMisuraDurata';

export interface Formazione { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dFine?: Date;
    dInizio?: Date;
    dInserim?: Date;
    denominazioneAziendaFormazione?: string;
    dsCorso: string;
    dsQualificaAcquisita?: string;
    durata?: number;
    flgFormazionePiemontese: string;
    flgInCorso?: string;
    flgPubblicazioneCorso?: string;
    flgTirocinioCurriculare: string;
    id?: number;
    idAttestazione?: Attestazione;
    idCandidatura: number;
    idComuneSedeCorso?: ComuneBlp;
    idNazioneSedeCorso?: NazioneBlp;
    idQualificaAcquisita?: QualificaBlp;
    idSilLavCorsoForm?: number;
    idToponimoSedeCorso?: ToponimoBlp;
    idUnitaMisuraDurata?: UnitaMisuraDurata;
    indirizzoSedeCorso?: string;
    numCivicoSedeCorso?: string;
}