/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallInfo } from './callInfo';
import { DidRidotta } from './didRidotta';
import { LavPqual } from './lavPqual';
import { LavSapDid } from './lavSapDid';
import { PattoDiServizio } from './pattoDiServizio';
import { SuntoLavoratore } from './suntoLavoratore';

export interface FormInserisciPatto { 
    callInfo?: CallInfo;
    dataFinePattoChiuso?: Date;
    dataFirmaPatto?: Date;
    dataPoliticaA02DaChiudere?: Date;
    did?: LavSapDid;
    didN00?: DidRidotta;
    idPattoChiuso?: number;
    idPoliticaA02DaChiudere?: number;
    idProfQuant?: number;
    idProfilingQualitativo?: number;
    idProfilingQuantitativo?: number;
    idSilLavAnagrafica?: number;
    isDidAllineataN00?: boolean;
    isProfQualRichiesto?: boolean;
    patto?: PattoDiServizio;
    profQual?: LavPqual;
    profilingQualitativoOrfano?: LavPqual;
    sunto?: SuntoLavoratore;
    tipoProgetto?: string;
}