/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallInfo } from './callInfo';
import { OperazioneFasciaPianificazioneOperatoreServizi } from './operazioneFasciaPianificazioneOperatoreServizi';

export interface GenerazionePianificazioneOperatoreServiziRequest { 
    callInfo?: CallInfo;
    dataFine?: Date;
    dataInizio?: Date;
    fase?: number;
    idOperatore?: string;
    idSilTCpi?: number;
    listaOperazioneFascia?: Array<OperazioneFasciaPianificazioneOperatoreServizi>;
}