/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Studio } from './studio';

export interface GradoStudio { 
    codIsced97?: string;
    codIsced97Level?: string;
    codLivello?: string;
    codMinistero?: string;
    codTitoloStudio?: string;
    dataFine?: Date;
    dataInizio?: Date;
    dsSilTGradoStudio?: string;
    dsSinonimiTitoloStudio?: string;
    dsTitoloStudio?: string;
    idSilTGradoStudio?: number;
    punteggio?: number;
    silTStudios?: Array<Studio>;
}