/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cpi } from './cpi';
import { PjSocieta } from './pjSocieta';
import { Provincia } from './provincia';

export interface InEnte { 
    dsTipoEnte?: string;
    idSilTInEnte?: number;
    idSilTRegione?: string;
    provincia?: Provincia;
    silPjSocieta?: PjSocieta;
    silTCpi?: Cpi;
}