/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AltreInformazioni } from './altreInformazioni';
import { ConoscenzaInformatica } from './conoscenzaInformatica';
import { Decodifica } from './decodifica';
import { LinguaStraniera } from './linguaStraniera';
import { PercorsoFormativo } from './percorsoFormativo';
import { QualificaInfoCv } from './qualificaInfoCv';

export interface InformazioniCurriculari { 
    altreInformazioni?: AltreInformazioni;
    conoscenzeInformatiche?: Array<ConoscenzaInformatica>;
    lingueStraniere?: Array<LinguaStraniera>;
    patenti?: Array<Decodifica>;
    patentini?: Array<Decodifica>;
    percorsoFormativo?: PercorsoFormativo;
    qualifiche?: Array<QualificaInfoCv>;
}