/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiMessage } from './apiMessage';
import { ProfilingQuant } from './profilingQuant';
import { StatoOccupazionale } from './statoOccupazionale';

export interface InserisciDidResponse { 
    abilitaDataPresuntoLicenziamento?: boolean;
    apiMessages?: Array<ApiMessage>;
    dataDomandaINPS?: Date;
    dataInizioSospensione?: Date;
    dataNascitaPiuParametro?: Date;
    esitoPositivo?: boolean;
    idDidINPS?: number;
    idPoliticaPresaInCaricoPiemonteSenzaPatto?: number;
    iscrizioneCOMI?: string;
    listStatoOccupazionale?: Array<StatoOccupazionale>;
    msgDomandaLegareDidINPS?: string;
    profQuantitativo?: ProfilingQuant;
    proponiDomandaQualitativo?: boolean;
    reddito?: number;
    sovrareddito?: string;
    tipoSovrareddito?: string;
    trovataPresaInCaricoPiemonteSenzaPatto?: boolean;
}