/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallInfo } from './callInfo';
import { LinguaDichCv } from './linguaDichCv';
import { LinguaStraniera } from './linguaStraniera';

export interface InserisciAggiornaLinguaCurriculumRequest { 
    callInfo?: CallInfo;
    idCv?: number;
    idSilLavAnagrafica?: number;
    lingua?: LinguaStraniera;
    linguaDichCV?: LinguaDichCv;
}