/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comune } from './comune';
import { Cpi } from './cpi';
import { LavAnagrafica } from './lavAnagrafica';
import { LavSapDid } from './lavSapDid';
import { StatoElaborazDid } from './statoElaborazDid';

export interface InterscambioDid { 
    codCapDom?: string;
    codFiscale?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataDichiarazione?: Date;
    dataFineTeorica?: Date;
    dataInserim?: Date;
    dataLegameDid?: Date;
    dsIndirizzoDom?: string;
    dsMail?: string;
    dsNote?: string;
    dsRecapiti?: string;
    flgAnnullato?: string;
    idSilInterscambio?: number;
    idSilLavProvvedimento?: number;
    idSilOperatore?: string;
    identificativoDid?: string;
    oggetto?: string;
    silLavAnagrafica?: LavAnagrafica;
    silLavSapDid?: LavSapDid;
    silTComuneDom?: Comune;
    silTCpiOper?: Cpi;
    silTStatoElaborazDid?: StatoElaborazDid;
    timestamp?: number;
}