/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CollaboratoreIntermediario } from './collaboratoreIntermediario';
import { ComuneBlp } from './comuneBlp';
import { CpiBlp } from './cpiBlp';
import { NazioneBlp } from './nazioneBlp';

export interface Intermediario { 
    capIntermediario?: string;
    cfIntermediario?: string;
    codIntermediario?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    collaboratoreIntermediarioList?: Array<CollaboratoreIntermediario>;
    dAggiorn?: Date;
    dInserim?: Date;
    dsIndirizzoIntermediario?: string;
    dsIntermediario?: string;
    emailIntermediario?: string;
    id?: number;
    idComune?: ComuneBlp;
    idCpi?: CpiBlp;
    idNazione?: NazioneBlp;
    numFaxIntermediario?: string;
    numTelIntermediario?: string;
}