/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface IscrizioneComi { 
    codFiscale?: string;
    codStatoIscrCatProt?: string;
    dataAggiorn?: Date;
    dataAnzianitaDal?: Date;
    dataCancellazione?: Date;
    dataInserim?: Date;
    dataIscrizione?: Date;
    dataStato?: Date;
    dsCognome?: string;
    dsNome?: string;
    dsProvincia?: string;
    dsSilTCpi?: string;
    dsSilTRegione?: string;
    dsStatoIscrCatProt?: string;
    dsTP?: string;
    flgSpeciale?: string;
    flgStato?: string;
    flgStatoFinale?: string;
    idIscriz?: string;
    idSilLavAnag?: number;
    idSilLavIscrCatProt?: number;
    idSilTCpiIscrizione?: number;
    idSilTProvincia?: string;
    idSilTRegione?: string;
    idTP?: string;
    tipo?: string;
    tipoIscr?: string;
    userAggiorn?: string;
}