/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ComuneBlp } from './comuneBlp';
import { LivelloStudio } from './livelloStudio';
import { NazioneBlp } from './nazioneBlp';
import { TitoloStudio } from './titoloStudio';
import { ToponimoBlp } from './toponimoBlp';

export interface IstruzioneDich { 
    annoCompletamento?: number;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dFine?: Date;
    dInizio?: Date;
    dInserim?: Date;
    descrizioneTitolo?: string;
    flgConseguitoInItalia?: string;
    flgInCorso: string;
    flgStagePcto: string;
    id?: number;
    idCandidatura: number;
    idComuneSedeIstituto?: ComuneBlp;
    idLivelloStudio: LivelloStudio;
    idNazioneSedeIstituto?: NazioneBlp;
    idTitoloStudio?: TitoloStudio;
    idToponimoIstituto?: ToponimoBlp;
    indirizzoIstituto?: string;
    nomeIstituto?: string;
    numCivicoIstituto?: string;
    votazioneConseguita?: string;
}