/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LivelloStudio } from './livelloStudio';
import { TitoloStudio } from './titoloStudio';

export interface IstruzioneRich { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    descrizioneTitolo?: string;
    flgPreferenzaRequisito: string;
    id?: number;
    idLivelloStudio: LivelloStudio;
    idTitoloStudio?: TitoloStudio;
    idVacancy: number;
}