/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Questura } from './questura';

export interface LavAnagraficaOld { 
    codCapDom?: string;
    codCapRes?: string;
    codFiscale?: string;
    codMcDebole?: string;
    codMcForte?: string;
    codSilTStatoOccup?: string;
    codSilTStatoOccupPadded?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    comuneDomicilio?: string;
    comuneNascita?: string;
    comuneResidenza?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dataMcAggiornDebole?: Date;
    dataMcAggiornForte?: Date;
    dataNasc?: Date;
    dataRichPermSogg?: Date;
    dataScadPermSogg?: Date;
    dataSchedaPers?: Date;
    dataServMil?: Date;
    dataUltMantenimentoIscr?: Date;
    dsAbilitazione?: string;
    dsAltraInformazione?: string;
    dsCognome?: string;
    dsCompetenza?: string;
    dsCreditoFormativo?: string;
    dsFileSchedaPers?: string;
    dsIndirizzoDigitale?: string;
    dsIndirizzoDom?: string;
    dsIndirizzoRes?: string;
    dsLocalitaDom?: string;
    dsLocalitaRes?: string;
    dsMail?: string;
    dsMailMin?: string;
    dsNome?: string;
    dsNote?: string;
    dsNoteB?: string;
    dsNoteStudioEstero?: string;
    dsNumCivicoDom?: string;
    dsNumCivicoRes?: string;
    dsNumDocPermSogg?: string;
    dsNumIndividuale?: string;
    dsSitoWeb?: string;
    dsSpecObbligoScol?: string;
    dsTelefonoCell?: string;
    dsTelefonoCellMin?: string;
    dsTelefonoDom?: string;
    dsTelefonoDomMin?: string;
    dsTelefonoFax?: string;
    dsTelefonoFaxMin?: string;
    dsTelefonoRes?: string;
    flgArchiviato?: string;
    flgCartaSogg?: string;
    flgContattoDirettoBlp?: string;
    flgDispBassaProf?: string;
    flgDispFormazione?: string;
    flgDispTirocinio?: string;
    flgGenere?: string;
    flgInformaticaBase?: string;
    flgLuogoNasc?: string;
    flgMezzoPLav?: string;
    flgMezzoPRagLav?: string;
    flgServMil?: string;
    flgValiditaCf?: string;
    fontedato?: number;
    idSilLavAnagrafica?: number;
    idSilTClasseOccupazione?: string;
    nazioneDomicilio?: string;
    nazioneNascita?: string;
    nazioneResidenza?: string;
    silTCategoria297?: number;
    silTCittadinanza?: string;
    silTCpiComp?: number;
    silTCpiProp?: number;
    silTGradoStudio?: number;
    silTMotRilPerm?: string;
    silTObbligoScol?: string;
    silTQuestura?: Questura;
    silTStatoCiv?: string;
    silTStatoObblForm?: number;
    silTStatusLavExtraUe?: string;
    timestamp?: number;
    toponimoDom?: string;
    toponimoRes?: string;
}