/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LavAnagraficaRidotta { 
    codiceFiscale?: string;
    codiceFiscalePrecedente?: string;
    cognome?: string;
    dataNascita?: Date;
    descrCittadinanza?: string;
    descrComDom?: string;
    descrComRes?: string;
    descrEnteTitolareSap?: string;
    descrNazione?: string;
    flgArchiviato?: string;
    fonteDato?: string;
    fonteUltimaModifica?: string;
    idCittadinanza?: string;
    idComDom?: string;
    idComRes?: string;
    idQuery?: string;
    idSilLavAnagrafica?: number;
    idSilTNazRes?: string;
    idSilTProvDom?: number;
    idSilTProvRes?: number;
    identificativoSap?: string;
    nome?: string;
    siglaProvDom?: string;
    siglaProvRes?: string;
}