/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Asl } from './asl';
import { CatalogArchivio } from './catalogArchivio';
import { Categoria297 } from './categoria297';
import { ChiamataProfQuant } from './chiamataProfQuant';
import { Cittadinanza } from './cittadinanza';
import { Comune } from './comune';
import { Cpi } from './cpi';
import { Fontedato } from './fontedato';
import { GradoStudio } from './gradoStudio';
import { Inps } from './inps';
import { InterscambioDid } from './interscambioDid';
import { LavIscrCatprotAltro } from './lavIscrCatprotAltro';
import { LavSapDid } from './lavSapDid';
import { LavSapSez6 } from './lavSapSez6';
import { ModoAssolv } from './modoAssolv';
import { MotRilPerm } from './motRilPerm';
import { Nazione } from './nazione';
import { ObbligoScol } from './obbligoScol';
import { PattoDiServizio } from './pattoDiServizio';
import { ProfilingQuant } from './profilingQuant';
import { Questura } from './questura';
import { RdcBeneficiario } from './rdcBeneficiario';
import { StatoCiv } from './statoCiv';
import { StatoObblForm } from './statoObblForm';
import { StatusLavExtraUe } from './statusLavExtraUe';
import { Toponimo } from './toponimo';

export interface LavAnagrafica { 
    codCapDom?: string;
    codCapRes?: string;
    codFiscale?: string;
    codMcDebole?: string;
    codMcForte?: string;
    codSilTStatoOccup?: string;
    codSilTStatoOccupPadded?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    comuneDomicilio?: Comune;
    comuneNascita?: Comune;
    comuneResidenza?: Comune;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dataMcAggiornDebole?: Date;
    dataMcAggiornForte?: Date;
    dataNasc?: Date;
    dataRichPermSogg?: Date;
    dataScadPermSogg?: Date;
    dataSchedaPers?: Date;
    dataServMil?: Date;
    dataUltMantenimentoIscr?: Date;
    dsAbilitazione?: string;
    dsAltraInformazione?: string;
    dsCognome?: string;
    dsCompetenza?: string;
    dsCreditoFormativo?: string;
    dsFileSchedaPers?: string;
    dsIndirizzoDigitale?: string;
    dsIndirizzoDom?: string;
    dsIndirizzoRes?: string;
    dsLocalitaDom?: string;
    dsLocalitaRes?: string;
    dsMail?: string;
    dsMailMin?: string;
    dsNome?: string;
    dsNote?: string;
    dsNoteB?: string;
    dsNoteStudioEstero?: string;
    dsNumCivicoDom?: string;
    dsNumCivicoRes?: string;
    dsNumDocPermSogg?: string;
    dsNumIndividuale?: string;
    dsSitoWeb?: string;
    dsSpecObbligoScol?: string;
    dsTelefonoCell?: string;
    dsTelefonoCellMin?: string;
    dsTelefonoDom?: string;
    dsTelefonoDomMin?: string;
    dsTelefonoFax?: string;
    dsTelefonoFaxMin?: string;
    dsTelefonoRes?: string;
    eta?: number;
    flgArchiviato?: string;
    flgCartaSogg?: string;
    flgContattoDirettoBlp?: string;
    flgDispBassaProf?: string;
    flgDispFormazione?: string;
    flgDispTirocinio?: string;
    flgGenere?: string;
    flgInformaticaBase?: string;
    flgLuogoNasc?: string;
    flgMezzoPLav?: string;
    flgMezzoPRagLav?: string;
    flgServMil?: string;
    flgValiditaCf?: string;
    idSilLavAnagrafica?: number;
    idSilTClasseOccupazione?: string;
    nazioneDomicilio?: Nazione;
    nazioneNascita?: Nazione;
    nazioneResidenza?: Nazione;
    silChiamataProfQuants?: Array<ChiamataProfQuant>;
    silInterscambioDids?: Array<InterscambioDid>;
    silLavIscrCatprotAltros?: Array<LavIscrCatprotAltro>;
    silLavSapDids?: Array<LavSapDid>;
    silLavSapSez6s?: Array<LavSapSez6>;
    silPattoDiServizios?: Array<PattoDiServizio>;
    silProfilingQuants?: Array<ProfilingQuant>;
    silRdcBeneficiarios?: Array<RdcBeneficiario>;
    silTAsl?: Asl;
    silTCatalogArchivio?: CatalogArchivio;
    silTCategoria297?: Categoria297;
    silTCittadinanza?: Cittadinanza;
    silTCpiComp?: Cpi;
    silTCpiProp?: Cpi;
    silTFontedato?: Fontedato;
    silTGradoStudio?: GradoStudio;
    silTInp?: Inps;
    silTModoAssolv?: ModoAssolv;
    silTMotRilPerm?: MotRilPerm;
    silTObbligoScol?: ObbligoScol;
    silTQuestura?: Questura;
    silTStatoCiv?: StatoCiv;
    silTStatoObblForm?: StatoObblForm;
    silTStatusLavExtraUe?: StatusLavExtraUe;
    timestamp?: number;
    toponimoDom?: Toponimo;
    toponimoRes?: Toponimo;
}