/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CertifCorso } from './certifCorso';
import { Comune } from './comune';
import { Nazione } from './nazione';
import { Regione } from './regione';
import { Toponimo } from './toponimo';

export interface LavCorsoFormAltro { 
    codTipologiaDurata?: string;
    codTipologiaDurataCorso?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dsAltraCertif?: string;
    dsDenominazioneAziStage?: string;
    dsDenominazioneEnteErog?: string;
    dsIndirizzoAziStage?: string;
    dsIndirizzoEnteErog?: string;
    dsNumCivicoAziStage?: string;
    dsNumCivicoEnteErog?: string;
    durataCorso?: number;
    durataStage?: number;
    flgLuogoAziStage?: string;
    flgLuogoEnteErog?: string;
    flgStageFinale?: string;
    idSilLavCorsoForm?: number;
    numHhDurata?: number;
    numMmDurata?: number;
    silTCertifCorso?: CertifCorso;
    silTComuneAziStage?: Comune;
    silTComuneEnteErog?: Comune;
    silTNazioneAgiStage?: Nazione;
    silTNazioneEnteErog?: Nazione;
    silTRegioneEnteErog?: Regione;
    silTRegioneSedeCorsoMin?: Regione;
    silTToponimoAziStage?: Toponimo;
    silTToponimoEnteErog?: Toponimo;
    timestamp?: number;
}