/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AmbDisciplinare } from './ambDisciplinare';
import { Fontedato } from './fontedato';
import { FormProf } from './formProf';
import { TipoApprendistato } from './tipoApprendistato';

export interface LavCorsoForm { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dFineCorso?: Date;
    dInizioCorso?: Date;
    dRitiro?: Date;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dsAnnoCorso?: string;
    dsQualifica?: string;
    flgAutocertificati?: string;
    flgPubblicazione?: string;
    idSilLavAnagrafica?: number;
    idSilLavCorsoForm?: number;
    numDurataTotaleIter?: number;
    numEsitoFinale?: number;
    numOreAssenza?: number;
    numParteIterAttuale?: number;
    silTAmbDisciplinare?: AmbDisciplinare;
    silTFontedato?: Fontedato;
    silTFormProf?: FormProf;
    silTTipoApprendistato?: TipoApprendistato;
    timestamp?: number;
}