/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CondizOccupazionale } from './condizOccupazionale';
import { Fontedato } from './fontedato';
import { LavAnagrafica } from './lavAnagrafica';
import { PresenzaInItaliaMin } from './presenzaInItaliaMin';
import { Provincia } from './provincia';
import { Studio } from './studio';

export interface LavDatiConferimDid { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataDid?: Date;
    dataEvento?: Date;
    dataInserim?: Date;
    durataDisoccupCalcolata?: number;
    eta?: number;
    flgAvutoAlmenoUnLav?: string;
    flgFigliAcarico?: string;
    flgFigliAcaricoMinori?: string;
    flgGenere?: string;
    flgPatente?: string;
    idCondizOccupCalcolata?: number;
    idSilLavDatiConferimDid?: number;
    idSilTCittadinanzaMin?: number;
    idSilTIscrizioneCorsoMin?: number;
    idSilTPosizioneProfMin?: number;
    numComponentiFamiglia?: number;
    numMesiFineUltimoRapp?: number;
    numMesiRicercaLav?: number;
    silLavAnagrafica?: LavAnagrafica;
    silTCondizOccupazionale?: CondizOccupazionale;
    silTFonteDato?: Fontedato;
    silTPresenzaInItaliaMin?: PresenzaInItaliaMin;
    silTProvincia?: Provincia;
    silTStudio?: Studio;
}