/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TipoDoc } from './tipoDoc';

export interface LavDocumento { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dataRilascio?: Date;
    dataScadenza?: Date;
    dsEnteRilascio?: string;
    dsNumeroDocumento?: string;
    idSilLavAnagrafica?: number;
    idSilLavDocumento?: number;
    timestamp?: number;
    tipoDoc?: TipoDoc;
}