/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TLavDatiStorici } from './tLavDatiStorici';

export interface LavDatiStorici { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dVariazione?: Date;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dsDatoPrecedente?: string;
    dsNote?: string;
    idSilLavAnagrafica?: number;
    idSilLavDatiStorici?: number;
    silTLavDatiStorici?: TLavDatiStorici;
    timestamp?: number;
}