/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comune } from './comune';
import { Nazione } from './nazione';
import { Toponimo } from './toponimo';

export interface LavEspExtraProf { 
    attivitaSvolte?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataAnnullamento?: Date;
    dataCessazEsp?: Date;
    dataInizioEsp?: Date;
    dataInserim?: Date;
    dsIndirizzoEnte?: string;
    dsNumCivicoEnte?: string;
    flgLuogoUtente?: string;
    idSilLavAnagrafica?: number;
    idSilLavEspExtraProf?: number;
    nomeEnte?: string;
    silTComuneEnte?: Comune;
    silTNazioneEnte?: Nazione;
    silTToponimoEnte?: Toponimo;
}