/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ateco02 } from './ateco02';
import { Ccnl } from './ccnl';
import { Comune } from './comune';
import { Fontedato } from './fontedato';
import { Grado } from './grado';
import { LivelloRetribuzione } from './livelloRetribuzione';
import { ModalitaLavoro } from './modalitaLavoro';
import { Nazione } from './nazione';
import { Qualifica } from './qualifica';
import { TipoApprendistato } from './tipoApprendistato';
import { TipoLavoro } from './tipoLavoro';
import { TipoParttime } from './tipoParttime';
import { Toponimo } from './toponimo';

export interface LavEsperienzaLavoro { 
    codFiscaleAu?: string;
    codFiscaleDl?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataFine?: Date;
    dataFinePeriodoFormativo?: Date;
    dataInizio?: Date;
    dataInserim?: Date;
    dsBenefAttivita?: string;
    dsDenominazioneAu?: string;
    dsDenominazioneDl?: string;
    dsDenominazioneRp?: string;
    dsIndirizzoAu?: string;
    dsIndirizzoDl?: string;
    dsIndirizzoLuogoLav?: string;
    dsLivello?: string;
    dsMansione?: string;
    dsNumCivicoAu?: string;
    dsNumCivicoDl?: string;
    dsNumCivicoLuogoLav?: string;
    dsSoggettoPromotore?: string;
    dsTipologCliente?: string;
    flgAssunzioneL68?: string;
    flgCoMin?: string;
    flgCv?: string;
    flgForma?: string;
    flgLavInMobilita?: string;
    flgLavoroAgricoltura?: string;
    flgLuogoAu?: string;
    flgLuogoDl?: string;
    flgResponPers?: string;
    flgStagionale?: string;
    idSilLavAnagrafica?: number;
    idSilLavEsperienzaLavoro?: number;
    numGgDurata?: number;
    numMinPartime?: number;
    numOreParttime?: number;
    silTAteco02?: Ateco02;
    silTAtecoAu?: Ateco02;
    silTCcnl?: Ccnl;
    silTComuneAu?: Comune;
    silTComuneDl?: Comune;
    silTComuneLuogoLav?: Comune;
    silTFontedato?: Fontedato;
    silTGrado?: Grado;
    silTLivelloRetribuzione?: LivelloRetribuzione;
    silTModalitaLavoro?: ModalitaLavoro;
    silTNazioneAu?: Nazione;
    silTNazioneDl?: Nazione;
    silTNazioneLuogoLav?: Nazione;
    silTQualifica?: Qualifica;
    silTTipoApprendistato?: TipoApprendistato;
    silTTipoLavoro?: TipoLavoro;
    silTToponimoAu?: Toponimo;
    silTToponimoDl?: Toponimo;
    silTToponimoLuogoLav?: Toponimo;
    timestamp?: number;
    tipoParttime?: TipoParttime;
}