/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CatProtetta } from './catProtetta';
import { Cpi } from './cpi';
import { Fontedato } from './fontedato';
import { LavAnagrafica } from './lavAnagrafica';
import { MotivoCancIscr } from './motivoCancIscr';
import { Provincia } from './provincia';

export interface LavIscrCatprotAltro { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    codiceBdcm?: string;
    dataAggiorn?: Date;
    dataAnzianitaDal?: Date;
    dataAttoCertificante?: Date;
    dataCancellazione?: Date;
    dataEstrazione?: Date;
    dataInserim?: Date;
    dataIscrizione?: Date;
    dsAttoCertificante?: string;
    dsMotivoCancellazione?: string;
    dsNoteCancellazione?: string;
    dsNoteIscrizione?: string;
    flgPrimaIscrizione?: string;
    flgStato?: string;
    idSilLavIscrCatprotAltro?: number;
    idSilLavRichIscr?: number;
    numIscrizioneProvinciale?: number;
    silLavAnagrafica?: LavAnagrafica;
    silTCatProtetta?: CatProtetta;
    silTCpi1?: Cpi;
    silTCpi2?: Cpi;
    silTFontedato?: Fontedato;
    silTMotivoCancIscr?: MotivoCancIscr;
    silTProvincia?: Provincia;
    timestamp?: number;
}