/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Fontedato } from './fontedato';
import { GradoConLin } from './gradoConLin';
import { LavAnagrafica } from './lavAnagrafica';
import { Lingua } from './lingua';
import { ModApprLin } from './modApprLin';

export interface LavLingua { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    flgCertificato?: string;
    fontedato?: Fontedato;
    gradoConLinL?: GradoConLin;
    idSilLavLingua?: number;
    silLavAnagrafica?: LavAnagrafica;
    silTGradoConLinP?: GradoConLin;
    silTGradoConLinS?: GradoConLin;
    silTLingua?: Lingua;
    silTModApprLin?: ModApprLin;
    timestamp?: number;
}