/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cpi } from './cpi';
import { LavAnagrafica } from './lavAnagrafica';
import { LavSapSez6 } from './lavSapSez6';
import { PqualPercorso } from './pqualPercorso';
import { PqualRisposta } from './pqualRisposta';
import { PqualSezione } from './pqualSezione';
import { StatoPqual } from './statoPqual';
import { TipoProgettoMin } from './tipoProgettoMin';

export interface LavPqual { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    codiceProfQuant?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dataProfQuant?: Date;
    dsNote?: string;
    dsValutazione?: string;
    dtPqual?: Date;
    dtStato?: Date;
    idSilOperatore?: string;
    idSilProfilingQuant?: number;
    idSilTRegione?: string;
    idSilwebLavPqual?: number;
    indiceProfQuant?: string;
    numPuntiAttribuiti?: number;
    sezionePuntiAttribuiti?: string;
    silLavAnagrafica?: LavAnagrafica;
    silLavSapSez6?: LavSapSez6;
    silTCpi?: Cpi;
    silTCpiTitolareSap?: Cpi;
    silTTipoProgettoMin?: TipoProgettoMin;
    silwebPqualRispostas?: Array<PqualRisposta>;
    silwebPqualSeziones?: Array<PqualSezione>;
    silwebTPqualPercorso?: PqualPercorso;
    silwebTStatoPqual?: StatoPqual;
    timestamp?: number;
}