/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClasseQuantMin } from './classeQuantMin';
import { Cpi } from './cpi';
import { FonteFinanzMin } from './fonteFinanzMin';
import { Fontedato } from './fontedato';
import { LavAnagrafica } from './lavAnagrafica';
import { Regione } from './regione';
import { TipoAttivitaMin } from './tipoAttivitaMin';
import { TipoProgettoMin } from './tipoProgettoMin';
import { TipologiaDurata } from './tipologiaDurata';

export interface LavSapSez6 { 
    codEntePromotore?: string;
    codTipologiaDurata?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataAnnullo?: Date;
    dataFine?: Date;
    dataInizio?: Date;
    dataInserim?: Date;
    dataProposta?: Date;
    dsNote?: string;
    dsPoliticaAttiva?: string;
    durata?: number;
    flgMinistero?: string;
    idSilInterscambio?: number;
    idSilLavAdesione?: number;
    idSilLavSapSez6?: number;
    identificativoPolitica?: string;
    identificativoPresaincarico?: string;
    indiceProfiling?: number;
    silLavAnagrafica?: LavAnagrafica;
    silTCpi?: Cpi;
    silTFonteFinanzMin?: FonteFinanzMin;
    silTFontedato?: Fontedato;
    silTProfilingQuantMin?: ClasseQuantMin;
    silTRegione?: Regione;
    silTTipoAttivitaMin?: TipoAttivitaMin;
    silTTipoProgettoMin?: TipoProgettoMin;
    silTTipologiaDurata?: TipologiaDurata;
    tipoAttivitaPolitica?: string;
    titoloDenominazione?: string;
}