/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LavAnagrafica } from './lavAnagrafica';
import { LavSapSez6 } from './lavSapSez6';
import { StatoSapDid } from './statoSapDid';

export interface LavSapDid { 
    codFonteMlps?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataAnnullo?: Date;
    dataDid?: Date;
    dataInaccettabilitaOld?: Date;
    dataInserim?: Date;
    dataPresuntaLicenziamento?: Date;
    dataRifiuto?: Date;
    dsNote?: string;
    flgCurrentRecord?: string;
    idSilLavSapDid?: number;
    idSilOperAnnullo?: string;
    idSilTCpiAnnullo?: number;
    listStatoSapDid?: Array<StatoSapDid>;
    silLavAnagrafica?: LavAnagrafica;
    silLavSapSez6?: LavSapSez6;
}