/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CatalogArchivio } from './catalogArchivio';
import { Cpi } from './cpi';

export interface LavStoricoCpi { 
    catalogArchivio?: CatalogArchivio;
    cpiComp?: Cpi;
    cpiProp?: Cpi;
    dataFineValidita?: Date;
    dsMotivoVariazione?: string;
    idSilLavAnagrafica?: number;
    idSilLavStoricoCpi?: number;
}