/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comune } from './comune';
import { Nazione } from './nazione';
import { Toponimo } from './toponimo';

export interface LavTitoloStudioAltro { 
    codTipologiaDurataStage?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dsDenominazioneAziStage?: string;
    dsDenominazioneIst?: string;
    dsIndirizzoAziStage?: string;
    dsIndirizzoIst?: string;
    dsNote?: string;
    dsNumCivicoAziStage?: string;
    dsNumCivicoIst?: string;
    dsRelatore?: string;
    dsTitoloTesi?: string;
    durataStage?: number;
    flgLuogoAziStage?: string;
    flgLuogoIst?: string;
    flgStageFinale?: string;
    idSilLavStudio?: number;
    silTComuneAziStage?: Comune;
    silTComuneIst?: Comune;
    silTNazioneAziStage?: Nazione;
    silTNazioneIst?: Nazione;
    silTToponimoAziStage?: Toponimo;
    silTToponimoIst?: Toponimo;
    timestamp?: number;
}