/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Fontedato } from './fontedato';
import { LavAnagrafica } from './lavAnagrafica';
import { Studio } from './studio';
import { TipoApprendistato } from './tipoApprendistato';

export interface LavTitoloStudio { 
    annoDiFrequenza?: number;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataFine?: Date;
    dataInizio?: Date;
    dataInserim?: Date;
    dsAnnoCompletato?: string;
    dsTitoloStudioSap?: string;
    dsVoto?: string;
    flgCompletato?: string;
    flgCumLaude?: string;
    flgPubblicazione?: string;
    flgRiconosciutoItalia?: string;
    idSilLavStudio?: number;
    idSilTTStatoTitoloStudio?: string;
    numAnniFrequentati?: number;
    numEsamiSostenuti?: number;
    silLavAnagrafica?: LavAnagrafica;
    silTFontedato?: Fontedato;
    silTStudio?: Studio;
    silTTipoApprendistato?: TipoApprendistato;
    timestamp?: number;
    ultimaClasseFrequentata?: string;
}