/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GradoConLingua } from './gradoConLingua';
import { LinguaBlp } from './linguaBlp';

export interface LinguaRich { 
    codGradoConLinLetto: GradoConLingua;
    codGradoConLinParlato: GradoConLingua;
    codGradoConLinScritto: GradoConLingua;
    codLingua: LinguaBlp;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dinserim?: Date;
    flgPreferenzaRequisito: string;
    id?: number;
    idVacancy: number;
}