/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GradoConLin } from './gradoConLin';
import { Lingua } from './lingua';
import { ModApprLin } from './modApprLin';

export interface LinguaDichCv { 
    codGradoConLingua?: GradoConLin;
    codLingua?: Lingua;
    flgCertificazioneAcquisita?: string;
    id?: number;
    idCandidatura?: number;
    idModApprLingua?: ModApprLin;
    tipoCertificazione?: string;
}