/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiMessage } from './apiMessage';
import { Decodifica } from './decodifica';
import { IncServizi } from './incServizi';

export interface ListaIncServiziResponse { 
    apiMessages?: Array<ApiMessage>;
    esitoPositivo?: boolean;
    listaCategorie?: Array<Decodifica>;
    listaIncServizi?: Array<IncServizi>;
}