/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ComuneBlp } from './comuneBlp';
import { Email } from './email';
import { StatoManifestazione } from './statoManifestazione';
import { ToponimoBlp } from './toponimoBlp';

export interface Manifestazione { 
    blpDComune?: ComuneBlp;
    blpDToponimo?: ToponimoBlp;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dFine?: Date;
    dFineIscrizioneEspositore?: Date;
    dInizio?: Date;
    dInizioGenerazioneBiglietti?: Date;
    dInizioIscrizioneCittadino?: Date;
    dInizioIscrizioneEspositore?: Date;
    dInserim?: Date;
    descrManifestazione?: string;
    dsLuogo?: string;
    durataSlotSpeechAziendale?: number;
    flgPresenzaParcheggio?: string;
    flgPubblicazioneSezioneOrientamento?: string;
    idDomandaDiIscrizioneEspositore?: number;
    idManifestazione?: number;
    imgLogo?: Array<string>;
    immagine?: Array<string>;
    indirizzo?: string;
    informazioniUtili?: string;
    iolavDEmail?: Email;
    iolavDStatoManifestazione?: StatoManifestazione;
    istruzioniUso?: string;
    nomeManifestazione?: string;
    numCivico?: string;
    testo1DettaglioAnnuncio?: string;
    testo2DettaglioAnnuncio?: string;
    testoAllegatiAccessoLibero?: string;
    testoAnnunciAccessoLibero?: string;
    testoEspositoriAccessoLibero?: string;
    testoIncontriAccessoLibero?: string;
}