/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AziAnagrafica } from './aziAnagrafica';
import { Cpi } from './cpi';
import { Fontedato } from './fontedato';
import { LavAnagrafica } from './lavAnagrafica';
import { Operatore } from './operatore';
import { TSoggNotiWeb } from './tSoggNotiWeb';
import { TTipoNotiWeb } from './tTipoNotiWeb';

export interface NotiWeb { 
    codSilwebTSoggNotiWebDestinatario?: TSoggNotiWeb;
    codSilwebTSoggNotiWebMittente?: TSoggNotiWeb;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataAnnullamento?: Date;
    dataInserim?: Date;
    dataLettura?: Date;
    dataNotifica?: Date;
    idSilwebNotiWeb?: number;
    oggSilwebTTipoNotiWeb?: string;
    silAziAnagrafica?: AziAnagrafica;
    silLavAnagrafica?: LavAnagrafica;
    silOperatore?: Operatore;
    silTCpiEntePromotore?: Cpi;
    silTCpiOperatore?: Cpi;
    silTFonteDato?: Fontedato;
    silwebTTipoNotiWeb?: TTipoNotiWeb;
    testoSilwebTTipoNotiWeb?: string;
    timestamp?: number;
}