/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Fontedato } from './fontedato';
import { LavSapDid } from './lavSapDid';
import { Provincia } from './provincia';
import { StatoSapDid } from './statoSapDid';

export interface Operatore { 
    codIncModificaOper?: string;
    codTipoOperatoreAddetto?: string;
    codUserAggiorn?: string;
    cognome?: string;
    dataAnnullamento?: Date;
    dataInserimento?: Date;
    dataUltimoAccesso?: Date;
    dsSilOperatore?: string;
    ente?: string;
    flagVisualizzabile?: string;
    flgIncPrenotaOper?: string;
    fontedato?: Fontedato;
    id?: string;
    lavSapDids?: Array<LavSapDid>;
    nome?: string;
    provincia?: Provincia;
    regione?: string;
    silOperatore?: string;
    statoSapDids?: Array<StatoSapDid>;
    timestamp?: number;
}