/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CatPercorso } from './catPercorso';
import { Cpi } from './cpi';
import { FonteFinanzMin } from './fonteFinanzMin';
import { Fontedato } from './fontedato';
import { InEnte } from './inEnte';
import { LavAnagrafica } from './lavAnagrafica';
import { LavSapDid } from './lavSapDid';
import { MotProfQual } from './motProfQual';
import { Otp } from './otp';
import { PattoIntermed } from './pattoIntermed';
import { PattoMisure } from './pattoMisure';
import { ProfilingQual } from './profilingQual';
import { ProfilingQualMin } from './profilingQualMin';
import { RdcBeneficiario } from './rdcBeneficiario';
import { TargetPatto } from './targetPatto';

export interface PattoDiServizio { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dMonitoraggio?: Date;
    dPadPadi?: Date;
    dSottoscrizione?: Date;
    dataAggiorn?: Date;
    dataFine?: Date;
    dataFirmaPds?: Date;
    dataInserim?: Date;
    dataPropostaPds?: Date;
    flgAnnullato?: string;
    flgCatPercorso?: string;
    flgPercettore?: string;
    idProfQualModif?: ProfilingQualMin;
    idSilOperatore?: string;
    idSilPjPattoDiServizio?: number;
    idSilPjSedeSocieta?: number;
    idSilPjSocieta?: number;
    pattoIntermediarioList?: Array<PattoIntermed>;
    pattoMisureList?: Array<PattoMisure>;
    rifLibra?: string;
    silLavAnagrafica?: LavAnagrafica;
    silLavSapDid?: LavSapDid;
    silProfilingQual?: ProfilingQual;
    silRdcBeneficiario?: RdcBeneficiario;
    silTCatPercorso?: CatPercorso;
    silTCpiTitolaritaSap?: Cpi;
    silTFonteFinanzMin?: FonteFinanzMin;
    silTFontedato?: Fontedato;
    silTInEnte?: InEnte;
    silTMotProfQual?: MotProfQual;
    silTOtp?: Otp;
    silTTargetPatto?: TargetPatto;
    silTTargetPattoInserim?: TargetPatto;
    silTTargetPattoSec?: TargetPatto;
}