/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InEnte } from './inEnte';
import { InTipoContatto } from './inTipoContatto';
import { IncServizi } from './incServizi';
import { LavAnagraficaRidotta } from './lavAnagraficaRidotta';
import { Operatore } from './operatore';
import { SedeEnte } from './sedeEnte';

export interface PianifLabor { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dAnnullamento?: Date;
    dInserim?: Date;
    dtOraIncontroLabor?: Date;
    durataMinutiIncontro?: number;
    idSilwebTPianifLabor?: number;
    listaPartecipanti?: Array<LavAnagraficaRidotta>;
    numDaErogare?: number;
    numDisdettiCittadino?: number;
    numDisdettiOperatore?: number;
    numErogati?: number;
    numMaxPartecLabor?: number;
    numMinPartecLabor?: number;
    numNonPresentati?: number;
    numSpostati?: number;
    oraFine?: string;
    oraInizio?: string;
    silOperatore?: Operatore;
    silTInEnteOperatore?: InEnte;
    silTInTipoContatto?: InTipoContatto;
    silwebTIncServizi?: IncServizi;
    silwebTSedeEnte?: SedeEnte;
    timestamp?: number;
}