/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';
import { IncServizi } from './incServizi';

export interface PianificazioneGiornaliera { 
    codFiscaleAnag?: string;
    dataGiorno?: string;
    decGiornoSettimana?: Decodifica;
    descrSilTInContattoIncontro?: string;
    descrSilwebTIncServiziAppunt?: string;
    descrStatoIncontro?: string;
    dsCognomeAnagAppunt?: string;
    dsNomeAnagAppunt?: string;
    dsSilwebTSedeEnte?: string;
    fineFascia?: string;
    finePeriodo?: Date;
    flgJolly?: string;
    flgPresenza?: string;
    flgRemoto?: string;
    giornoSettimana?: string;
    idIncontro?: number;
    idOperatore?: string;
    idQry?: string;
    idSilLavAnagraficaAppunt?: number;
    idSilTCpi?: number;
    idSilpwebTIncServiziAppunt?: number;
    idSilwebTSedeEnte?: number;
    inizioFascia?: string;
    inizioPeriodo?: Date;
    listaServizi?: Array<IncServizi>;
    statoSlot?: string;
}