/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SilTProvincia } from './silTProvincia';

export interface PjSocieta { 
    codFp?: number;
    codOperatoreFp?: number;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataFine?: Date;
    dataInizio?: Date;
    dataInserim?: Date;
    descr?: string;
    flgEnteAccreditato?: string;
    flgModificabile?: string;
    gruppoOperatoreFp?: string;
    id?: number;
    pIvaCf?: string;
    provincia?: SilTProvincia;
    timestamp?: number;
}