/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PoliticaA02 { 
    codEntePromotore?: string;
    dataEvento?: Date;
    dataFine?: Date;
    dataInizio?: Date;
    dataProposta?: Date;
    descrFonte?: string;
    descrFonteFinanzMin?: string;
    descrProfQualitativo?: string;
    dsSilTRegione?: string;
    dsSilTTipoEventoSez6?: string;
    entePromotMin?: string;
    flgFinale?: string;
    idSilLav?: number;
    idSilLavSapSez6?: number;
    idSilTFonte?: number;
    idSilTFonteFinanzMin?: number;
    idSilTRegione?: string;
    idSilTTipoAttivita?: number;
    idSilTTipoEventoSez6?: number;
    idSilTTipoProgetto?: number;
    identificativoPolitica?: string;
    identificativoPresaInCarico?: string;
    indiceProfiling?: string;
    progettoMin?: string;
    statoDid?: string;
}