/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';

export interface Posizione { 
    categoriaDlg297?: Decodifica;
    condizioneOccupazionale?: Decodifica;
    dataAggiornamento?: Date;
    dataDid?: Date;
    dataEvento?: Date;
    fonte?: Decodifica;
    indiceProfiling?: Decodifica;
    mesiAnzianitaDisoccup?: string;
    statoOccupazionale?: Decodifica;
}