/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Funzione } from './funzione';

export interface Privacy { 
    codPrivacy?: string;
    dFine?: Date;
    dInizio?: Date;
    descPrivacy?: string;
    dsDettaglio?: string;
    dsSunto?: string;
    dsTestata?: string;
    idPrivacy?: number;
    pslpDFunzione?: Funzione;
}