/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AltraDisponibilita } from './altraDisponibilita';
import { DisponibilitaOrario } from './disponibilitaOrario';
import { DisponibilitaSpostamento } from './disponibilitaSpostamento';
import { DisponibilitaSpostamentoComune } from './disponibilitaSpostamentoComune';
import { DisponibilitaSpostamentoCpi } from './disponibilitaSpostamentoCpi';
import { DisponibilitaSpostamentoNazione } from './disponibilitaSpostamentoNazione';
import { DisponibilitaSpostamentoProvincia } from './disponibilitaSpostamentoProvincia';
import { DisponibilitaSpostamentoRegione } from './disponibilitaSpostamentoRegione';
import { PreferenzaTipoLavoro } from './preferenzaTipoLavoro';
import { PropensioniDatiPreferenza } from './propensioniDatiPreferenza';
import { PropensioniDatiQualifica } from './propensioniDatiQualifica';

export interface PropensioniPreferenzeQualifica { 
    idPreferenza?: number;
    listaAltraDisponibilita?: Array<AltraDisponibilita>;
    listaDispOrario?: Array<DisponibilitaOrario>;
    listaDispSpostamento?: Array<DisponibilitaSpostamento>;
    listaDispSpostamentoComune?: Array<DisponibilitaSpostamentoComune>;
    listaDispSpostamentoCpi?: Array<DisponibilitaSpostamentoCpi>;
    listaDispSpostamentoNazione?: Array<DisponibilitaSpostamentoNazione>;
    listaDispSpostamentoProvincia?: Array<DisponibilitaSpostamentoProvincia>;
    listaDispSpostamentoRegione?: Array<DisponibilitaSpostamentoRegione>;
    listaPreferenzatipoLavoro?: Array<PreferenzaTipoLavoro>;
    preferenza?: PropensioniDatiPreferenza;
    qualifica?: PropensioniDatiQualifica;
}