/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Regione } from './regione';

export interface Provincia { 
    dataFine?: Date;
    dataInizio?: Date;
    descr?: string;
    dsSiglaProvincia?: string;
    flgAttivo?: string;
    idSilTElencoEnti?: string;
    idSilTProvincia?: string;
    regione?: Regione;
}