/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DatoreAzienda } from './datoreAzienda';
import { InformazioniGenerali } from './informazioniGenerali';
import { Lavoratore } from './lavoratore';

export interface RapportoLavoroAttivo { 
    datoreAzienda?: DatoreAzienda;
    informazioniGenerali?: InformazioniGenerali;
    lavoratore?: Lavoratore;
}