/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ComunicazioneObbligatoriaXRapporti } from './comunicazioneObbligatoriaXRapporti';
import { DettaglioStorico } from './dettaglioStorico';

export interface RapportoDiLavoro { 
    codiceFiscaleAzienda?: string;
    comunicazioniObbligatorie?: Array<ComunicazioneObbligatoriaXRapporti>;
    contratto?: string;
    dataFine?: Date;
    dataInizioRapporto?: Date;
    denominazioneAzienda?: string;
    desComuneDatoreLavoro?: string;
    dettaglioStoricoRapportoDiLavoro?: DettaglioStorico;
    durata?: number;
    flgRapportoCessato?: string;
    idAssunzione?: number;
    idSilStoricoRapportoLavoro?: number;
    indirizzoDatoreLavoro?: string;
    partTime?: string;
}