/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RdcBeneficiario { 
    cfBeneficiario?: string;
    cfRichiedente?: string;
    codCapDomicilio?: string;
    codCapResidenza?: string;
    codCittadinanza?: string;
    codComuneDomicilio?: string;
    codComuneNascita?: string;
    codComuneResidenza?: string;
    codProtocInpsPrec?: string;
    codRdcTipoBenef?: string;
    codSap?: string;
    codStatoDomanda?: string;
    codTipoDomanda?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dTrasformazione?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dataNascita?: Date;
    dataVariazioneStato?: Date;
    dsCognomeBenef?: string;
    dsComuneDomicilio?: string;
    dsComuneNascita?: string;
    dsComuneResidenza?: string;
    dsEmail?: string;
    dsIndirizzoDomicilio?: string;
    dsIndirizzoResidenza?: string;
    dsNomeBenef?: string;
    dsTelefono?: string;
    fonte?: string;
    idSilRdcBeneficiario?: number;
    idSilRdcDomanda?: number;
    idSilRdcNotifica?: number;
    sesso?: string;
}