/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FonteAggiornamento } from './fonteAggiornamento';

export interface Recapito { 
    cellulare?: string;
    cellulare2?: string;
    email?: string;
    fonteAggiornamento?: FonteAggiornamento;
    indirizzoDigitale?: string;
    telefonoAbitazione?: string;
}