/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiMessage } from './apiMessage';

export interface ReportResponse { 
    apiMessages?: Array<ApiMessage>;
    bytes?: Array<string>;
    esitoPositivo?: boolean;
    fileNameTemplate?: string;
    mimeTypeContainer?: ReportResponse.MimeTypeContainerEnum;
}
export namespace ReportResponse {
    export type MimeTypeContainerEnum = 'EXCEL_WORKBOOK' | 'EXCEL_SPREADSHEET' | 'PDF';
    export const MimeTypeContainerEnum = {
        EXCELWORKBOOK: 'EXCEL_WORKBOOK' as MimeTypeContainerEnum,
        EXCELSPREADSHEET: 'EXCEL_SPREADSHEET' as MimeTypeContainerEnum,
        PDF: 'PDF' as MimeTypeContainerEnum
    };
}