/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiMessage } from './apiMessage';
import { OperatorePiuScaricoSlot } from './operatorePiuScaricoSlot';
import { PianifLabor } from './pianifLabor';
import { SlotLiberiMensileRidotta } from './slotLiberiMensileRidotta';
import { SlotLiberiRidotta } from './slotLiberiRidotta';

export interface RicercaSlotLiberiPrenotabiliResponse { 
    apiMessages?: Array<ApiMessage>;
    dataFinePeriodoQry?: Date;
    dataInizioPeriodoQry?: Date;
    dataMassimaDisponibilita?: Date;
    dataMinimaDisponibilita?: Date;
    esitoPositivo?: boolean;
    listMensileSlot?: Array<SlotLiberiMensileRidotta>;
    listOperatori?: Array<OperatorePiuScaricoSlot>;
    listPianifLabor?: Array<PianifLabor>;
    listSlot?: Array<SlotLiberiRidotta>;
    operazione?: string;
    oraIncontroQry?: string;
    primaDataUtile?: Date;
    titoloCalendario?: string;
    ultimaDataUtile?: Date;
}