/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comune } from './comune';
import { InEnte } from './inEnte';
import { TipoSede } from './tipoSede';
import { Toponimo } from './toponimo';

export interface SedeEnte { 
    codCap?: string;
    codFiscale?: string;
    codPartitaIva?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dFine?: Date;
    dInizio?: Date;
    dInserim?: Date;
    dsAltroTelefono?: string;
    dsComeRaggiungerci?: string;
    dsEmail?: string;
    dsFacebook?: string;
    dsFax?: string;
    dsIndirizzo?: string;
    dsInstagram?: string;
    dsNote?: string;
    dsNumCivico?: string;
    dsNumeroVerde?: string;
    dsResponsabileCognome?: string;
    dsResponsabileNome?: string;
    dsTelefono?: string;
    idSilwebTSedeEnte?: number;
    silTComune?: Comune;
    silTInEnte?: InEnte;
    silTToponimo?: Toponimo;
    silwebDTipoSede?: TipoSede;
    subCodiceSede?: number;
    timestamp?: number;
}