/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SilTAteco02 } from './silTAteco02';
import { SilTCcnl } from './silTCcnl';
import { SilTNaturaGiuridica } from './silTNaturaGiuridica';
import { SilTTipoAzienda } from './silTTipoAzienda';

export interface SilAziAnagrafica { 
    ccnl?: SilTCcnl;
    codFiscale?: string;
    codMcDebole?: string;
    codMcForte?: string;
    codPartitaIva?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    dataMcAggiornDebole?: Date;
    dataMcAggiornForte?: Date;
    descAltreInformazioni?: string;
    descAnilt?: string;
    descrDenominazione?: string;
    flgArtigiana?: string;
    flgAziEstera?: string;
    flgMaster?: string;
    flgPubblAmmin?: string;
    flgValiditaCf?: string;
    flgValiditaPiva?: string;
    idSilAziAnagrafica?: number;
    pec?: string;
    silTAteco02?: SilTAteco02;
    silTNaturaGiuridica?: SilTNaturaGiuridica;
    silTTipoAzienda?: SilTTipoAzienda;
    timestamp?: number;
}