/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SilTProvincia } from './silTProvincia';

export interface SilOperatore { 
    codIncModificaOper?: string;
    codTipoOperatoreAddetto?: string;
    codUserAggiorn?: string;
    dataAnnullamento?: Date;
    dataInserimento?: Date;
    dataUltimoAccesso?: Date;
    dsCognome?: string;
    dsEnte?: string;
    dsNome?: string;
    dsSilOperatore?: string;
    flgIncPrenotaOper?: string;
    flgVisualizzabile?: string;
    idSilOperatore?: string;
    idSilTRegione?: string;
    silTProvincia?: SilTProvincia;
    timestamp?: number;
}