/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SilPjSocieta } from './silPjSocieta';
import { SilTCpi } from './silTCpi';
import { SilTProvincia } from './silTProvincia';

export interface SilTInEnte { 
    dsTipoEnte?: string;
    idSilTInEnte?: number;
    idSilTRegione?: string;
    provincia?: SilTProvincia;
    silPjSocieta?: SilPjSocieta;
    silTCpi?: SilTCpi;
}