/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SilTAsl } from './silTAsl';
import { SilTCpi } from './silTCpi';
import { SilTInps } from './silTInps';
import { SilTProvincia } from './silTProvincia';
import { SilTRegione } from './silTRegione';

export interface SilTComune { 
    codCap?: string;
    codIstat?: string;
    codPrefisso?: string;
    codProv?: string;
    dataFine?: Date;
    dataInizio?: Date;
    descr?: string;
    flgAttivo?: string;
    id?: string;
    silTAsl?: SilTAsl;
    silTCpi?: SilTCpi;
    silTInps?: SilTInps;
    silTProvincia?: SilTProvincia;
    silTRegione?: SilTRegione;
}