/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SilwebTServizioIncontri { 
    codTokenGam?: number;
    codUserAggiorn?: string;
    codUserInserim?: string;
    daggiorn?: Date;
    desito?: Date;
    dincontro?: Date;
    dinserim?: Date;
    dsAltroLuogo?: string;
    dsIndirizzoEsteso?: string;
    dsNote?: string;
    flgBackoffice?: string;
    idMessaggioDisdettaOper?: string;
    idMessaggioNonPresen?: string;
    idMessaggioPrenotaz?: string;
    idMessaggioPromemoria?: string;
    idSilLavAnagrafica?: number;
    idSilOperatoreAdd?: string;
    idSilTCpiPromotore?: number;
    idSilTFontedato?: number;
    idSilTInEnteOperatoreAdd?: number;
    idSilTInMotivazione?: number;
    idSilTInTipoContatto?: number;
    idSilTStatoIncon?: string;
    idSilTStatoInconRich?: string;
    idSilwebDStatoChiamataGam?: string;
    idSilwebTGruppiServizi?: number;
    idSilwebTIncServizi?: number;
    idSilwebTSedeEnte?: number;
    idSilwebTServIncontPrec?: number;
    idSilwebTServiziPai?: number;
    idSilwebTServizioIncontri?: number;
    idSilwebTSoggVincitori?: number;
    numDurataEffettiva?: number;
    numDurataEffettivaRich?: number;
    numDurataPrevista?: number;
    numOrarioDa?: number;
    timestamp?: number;
}