/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SilOperatore } from './silOperatore';
import { SilTInEnte } from './silTInEnte';
import { SilTInTipoContatto } from './silTInTipoContatto';
import { SilwebTServizioIncontri } from './silwebTServizioIncontri';

export interface SilwebTStoServIncontri { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    daggiorn?: Date;
    dinserim?: Date;
    dtVariazione?: Date;
    idSilwebTStoServIncontri?: number;
    silOperatoreAdd?: SilOperatore;
    silTInEnteOperatoreAdd?: SilTInEnte;
    silTInTipoContatto?: SilTInTipoContatto;
    silwebTServizioIncontri?: SilwebTServizioIncontri;
    timestamp?: number;
}