/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface StatoDidByCo { 
    codFiscale?: string;
    codSilTTuTipoMissione?: string;
    codVariazione?: string;
    dataCambioMissione?: Date;
    dataCessazioneMissione?: Date;
    dataComunicazione?: Date;
    dataFineMissione?: Date;
    dataFineProrogaMissione?: Date;
    dataFineRapporto?: Date;
    dataInizioMissione?: Date;
    dataInizioProroga?: Date;
    dataInizioRapporto?: Date;
    dataRientroCambioMissione?: Date;
    dataTrasformazione?: Date;
    dsSilTTipoLavoro?: string;
    dsSilTTuTipoMissione?: string;
    idSilComunicAssunz?: number;
    idSilLavAnagrafica?: number;
    idSilStoricoRapportoLavoro?: number;
    idSilTComunicazione?: string;
    idSilTRapportoLavoro?: string;
    idSilTTipoLavoro?: string;
    idSilTTuTipoMissione?: number;
    numDurata?: number;
    numImpRedditoLordo?: number;
    numRetribuzioneLorda?: number;
    numRetribuzioneLordaAnnua?: number;
    retribuzioneMissione?: number;
}