/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClasseOccupMin } from './classeOccupMin';
import { ClasseQuantMin } from './classeQuantMin';
import { Cpi } from './cpi';
import { Fontedato } from './fontedato';
import { LavSapDid } from './lavSapDid';
import { MotivoStatoDid } from './motivoStatoDid';
import { StatoDid } from './statoDid';
import { StatoOccupMin } from './statoOccupMin';

export interface StatoSapDid { 
    codEntePromotore?: string;
    codEntePromotoreOp?: string;
    codStatoDid?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    codUserRicalcolo?: string;
    dataAggiorn?: Date;
    dataAnnullamento?: Date;
    dataAnzianita?: Date;
    dataEvento?: Date;
    dataInserim?: Date;
    dataRicalcolo?: Date;
    dataRifiuto?: Date;
    dataStato?: Date;
    dsNote?: string;
    dsNoteStatoNoConferim?: string;
    flgConferito?: string;
    flgCurrentRecord?: string;
    flgSottoReddito?: string;
    idEnteRifiuto?: number;
    idSilChiamataConferimDid?: number;
    idSilOperAnnullo?: string;
    idSilTCpiAnnullo?: number;
    idStatoSapDid?: number;
    indiceProfiling?: number;
    motivoRifiuto?: string;
    numGiorniAnzianita?: number;
    numMesiAnzCalcolati?: number;
    numMesiAnzianita?: number;
    numTotRedditoProspettico?: number;
    operatoreRifiuto?: string;
    showIconAnnullaDid?: boolean;
    showIconConferireDid?: boolean;
    silLavSapDid?: LavSapDid;
    silTClasseOccupMin?: ClasseOccupMin;
    silTCpi?: Cpi;
    silTCpiOp?: Cpi;
    silTFontedato?: Fontedato;
    silTProfilingQuantMin?: ClasseQuantMin;
    silTStatoDid?: StatoDid;
    silTStatoOccupMin?: StatoOccupMin;
    silwebTMotivoStatoDid?: MotivoStatoDid;
}