/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClasseOccupMin } from './classeOccupMin';
import { StatoOccupMin } from './statoOccupMin';

export interface StatoOccupazionale { 
    classeCondizioneOccupazionale?: ClasseOccupMin;
    condizioneOccupazionale?: StatoOccupMin;
    dataStatoDID?: Date;
    flgSottoReddito?: string;
    flgSovraredditoAutonomo?: string;
    flgSovraredditoCoCoCo?: string;
    flgSovraredditoMisto?: string;
    flgSovraredditoSubordinato?: string;
    retribProspettAnnua?: number;
    statoDID?: string;
}