/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Messaggio } from './messaggio';
import { Regola } from './regola';

export interface StepFlusso { 
    codApplicaRegola?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataInserim?: Date;
    flgAttiva?: string;
    idMessaggioFalso?: Messaggio;
    idMessaggioVero?: Messaggio;
    idSilwebRStepFlusso?: number;
    idStepFlussoPrecedente?: number;
    idStepFlussoSuccFalso?: number;
    idStepFlussoSuccVero?: number;
    silwebDRegola?: Regola;
    timestamp?: number;
}