/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AziSede } from './aziSede';
import { Grado } from './grado';
import { StoricoRapportoLavoro } from './storicoRapportoLavoro';
import { TipoApprendistato } from './tipoApprendistato';

export interface StoricoRappDipendente { 
    dCambioMissione?: Date;
    dFineApprendistato?: Date;
    dInizioSospensione?: Date;
    dRegCommDomm?: Date;
    dRientroCambioMissione?: Date;
    dRientroDaSospensione?: Date;
    dRientroDaTrasferimento?: Date;
    dTrasferimento?: Date;
    dVariazioneGradoQualifica?: Date;
    dVisitaMedica?: Date;
    dsNoteMotivo?: string;
    dsPatInailSedeUtilizzat?: string;
    dsRegCommDomm?: string;
    flgDistaccoAziendaEstera?: string;
    flgDistaccoParziale?: string;
    flgIndennitaDisponiblita?: string;
    flgTelelavoro?: string;
    flgVisitaIspettiva?: string;
    idSilARicA16SLavStato?: number;
    idSilAziAcfl?: number;
    idSilAziAci?: number;
    idSilAziL68ComConvenzione?: number;
    idSilLavDatiComPregressi?: number;
    idSilStoricoRapportoLavoro?: number;
    idSilTCategoriaLav?: string;
    idSilTModoAss?: number;
    idSilTMotivoStoricoTd?: number;
    idSilTNormAss?: number;
    idSilTNormAssMis?: number;
    idSilTTuTipoMissione?: number;
    idSilTutoreApprendistato?: number;
    numAgenziaSomministrazione?: number;
    numGgDurataCambioMissione?: number;
    numIndennitaDisponibilita?: number;
    numMatricolaLav?: string;
    numRetribuzioneLorda?: number;
    numRetribuzioneLordaAnnua?: number;
    silAziSedeUtilizzatrice?: AziSede;
    silStoricoRapportoLavoro?: StoricoRapportoLavoro;
    silTGrado?: Grado;
    silTTipoApprendistato?: TipoApprendistato;
}