/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Agevolazione } from './agevolazione';
import { AziSede } from './aziSede';
import { Ccnl } from './ccnl';
import { ComunicazioneDto } from './comunicazioneDto';
import { EntePrevidenziale } from './entePrevidenziale';
import { LivelloRetribuzione } from './livelloRetribuzione';
import { MotivoComunicazione } from './motivoComunicazione';
import { Qualifica } from './qualifica';
import { RapportoLavoro } from './rapportoLavoro';
import { TipoLavoro } from './tipoLavoro';
import { TipoParttime } from './tipoParttime';

export interface StoricoRapportoLavoro { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dataAggiorn?: Date;
    dataFineRapporto?: Date;
    dataInizioProroga?: Date;
    dataInizioRapporto?: Date;
    dataInserim?: Date;
    dataTrasformazione?: Date;
    descrCodAltroEntePrevidenzial?: string;
    descrLivello?: string;
    descrLuogoLavoro?: string;
    descrMansione?: string;
    descrPatInail?: string;
    flgAssunzioneL68?: string;
    flgCurrentRecord?: string;
    flgForma?: string;
    flgLavInMobilita?: string;
    flgLavoroAgricoltura?: string;
    flgProsecuzioneDiFatto?: string;
    flgPubblicareSuCurriculum?: string;
    flgResponsabileAltrePersone?: string;
    flgSocioLavoratore?: string;
    flgStagionale?: string;
    idSilLavAnagrafica?: number;
    idSilStoricoRapportoLavoro?: number;
    numGgAgricoltura?: number;
    numGgDurata?: number;
    numMinParttimeSettimanali?: number;
    numOreParttimeSettimanali?: number;
    silAziSede?: AziSede;
    silComunicAssunz?: ComunicazioneDto;
    silComunicGenerante?: ComunicazioneDto;
    silRappStoricoOriginario?: StoricoRapportoLavoro;
    silStoricoRappPrecedente?: StoricoRapportoLavoro;
    silTAgevolazioneOld?: Agevolazione;
    silTCcnl?: Ccnl;
    silTEntePrevidenziale?: EntePrevidenziale;
    silTLivelloRetribuzione?: LivelloRetribuzione;
    silTMotivoComunicazione?: MotivoComunicazione;
    silTQualifica?: Qualifica;
    silTRapportoLavoro?: RapportoLavoro;
    silTTipoLavoro?: TipoLavoro;
    silTTipoParttime?: TipoParttime;
    timestamp?: number;
}