/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SuntoLavoratore { 
    codEventoN00?: string;
    codFisc?: string;
    codIntermediarioMin?: string;
    codStatoDid?: string;
    codiceQuantPatto?: string;
    cognome?: string;
    comuneResidenzaRdc?: string;
    dataAnzianitaCatProtetta?: Date;
    dataAnzianitaDid?: Date;
    dataAnzianitaDisabile?: Date;
    dataDidInps?: Date;
    dataDomandaSFL?: Date;
    dataEventoN00?: Date;
    dataFine?: Date;
    dataFirma?: Date;
    dataIscrizioneCatProtetta?: Date;
    dataNascita?: Date;
    dataPropostaN00?: Date;
    dataRdc?: Date;
    dataSapErr?: Date;
    dataSapOk?: Date;
    dataStatoDid?: Date;
    dataStatoSFL?: Date;
    dataUltAggSapErr?: Date;
    dataUltAggSapOk?: Date;
    datatDid?: Date;
    datatIscrizioneDisabile?: Date;
    desEventoN00?: string;
    desQualPatto?: string;
    desQualPattoModificato?: string;
    desQuantPatto?: string;
    desStatoRdc?: string;
    descrStatoDid?: string;
    dsCpi?: string;
    dtCalcQualPatto?: Date;
    dtCalcQuantPatto?: Date;
    eta?: number;
    flagFinaleSFL?: string;
    flgConferitoDid?: string;
    flgEventoFinaleN00?: string;
    flgStatoFinaleDid?: string;
    flgStatoFinaleIscrCat?: string;
    flgStatoFinaleIscrDis?: string;
    flgStatoFinaleRdc?: string;
    idInterscSapErr?: number;
    idInterscSapOk?: number;
    idPoliticaQualPatto?: string;
    idRegioneDomic?: string;
    idSilLavAnagrafica?: number;
    invaliditaPrev?: string;
    nome?: string;
    profQuantCalcolo?: string;
    profQuantClasse?: string;
    profQuantCodice?: string;
    statoCatProtetta?: string;
    statoCodSFL?: string;
    statoDesSapErr?: string;
    statoDescSFL?: string;
    statoDisabile?: string;
    statoRdc?: string;
    totComuBlocc?: number;
    totComuScart?: number;
}