/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Target } from './target';
import { TipoPercettore } from './tipoPercettore';
import { TipoProgettoMin } from './tipoProgettoMin';

export interface TargetPatto { 
    dFine?: Date;
    dInizio?: Date;
    flgDid?: string;
    flgRdc?: string;
    idSilTTarget?: number;
    silTTarget?: Target;
    silTTipoPercettore?: TipoPercettore;
    silTTipoProgettoMin?: TipoProgettoMin;
}