/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatoDid } from './statoDid';

export interface TipoEventoSez6 { 
    codTipoEventoSez6Min?: string;
    dataFine?: Date;
    dataInizio?: Date;
    dsSilTTipoEventoSez6?: string;
    dsTipoEventoSez6Min?: string;
    flgFinale?: string;
    flgMotivoObbl?: string;
    idSilTTipoEventoSez6?: number;
    silTStatoDid?: StatoDid;
    tipoUtilizzoRdc?: string;
}