/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TipoCheck { 
    COD_SILWEB_D_TIPO_CHECK?: string;
    DES_SILWEB_D_TIPO_CHECK?: string;
    D_FINE?: Date;
    D_INIZIO?: Date;
    ID_SILWEB_D_TIPO_CHECK?: number;
}