/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TipoLavoro { 
    dataFine?: Date;
    dataInizio?: Date;
    dsSilTTipoLavoro?: string;
    flgAssegnazione?: string;
    flgAutorizzCfl?: string;
    flgAutorizzProgIns?: string;
    flgCateg?: string;
    flgCessato?: string;
    flgDenominazione?: string;
    flgForma?: string;
    flgFormaDefault?: string;
    flgGgAgricoltura?: string;
    flgIndennitaDisp?: string;
    flgMissione?: string;
    flgMobilita?: string;
    flgModAssunz?: string;
    flgNormAssunz?: string;
    flgPreferenza?: string;
    flgProgetto?: string;
    flgSocioLavoratore?: string;
    flgSoggettoPromotore?: string;
    flgStagionale?: string;
    flgTipoApprendistato?: string;
    flgTipoAzienda?: string;
    flgTipoLavoro?: string;
    flgTipoParttime?: string;
    idSilTTipoLavoro?: string;
}