/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TipoParttime { 
    codMinisteriale?: string;
    codMinistero?: string;
    dataFine?: Date;
    dataInizio?: Date;
    dsMinistero?: string;
    dsSilTTipoParttime?: string;
    flgFasciaOraria?: string;
    idSilTModalitaLavoro?: number;
    idSilTTipoParttime?: string;
    nMaxFasce?: number;
    tabellaFasce?: string;
}