/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TipoCheck } from './tipoCheck';

export interface TipoDocume { 
    codUtilizzo?: string;
    dFine?: Date;
    dInizio?: Date;
    desSilwebTTipoDocume?: string;
    durataStampaGg?: number;
    flOtp?: string;
    flgAbilitazionePslp?: string;
    flgInvioAppio?: string;
    flgInvioMail?: string;
    flgIstruttoria?: string;
    flgLibra?: string;
    flgRepertorio?: string;
    ggDurataAutocertPslp?: number;
    ggDurataAutocertSilp?: number;
    idSilwebTTipoDocume?: number;
    silwebDTipoCheckAutoc?: TipoCheck;
    silwebDTipoCheckContr?: TipoCheck;
    testoMsgInformativoPslp?: string;
}