/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';
import { LavTitoloStudio } from './lavTitoloStudio';

export interface TitoloDiStudio { 
    annoCompletato?: string;
    codice?: string;
    completato?: string;
    descrizioneTitolo?: string;
    flgCv?: string;
    flgProfQuant?: string;
    gradoStudio?: Decodifica;
    idTitoloStudio?: number;
    lavTitoloStudio?: LavTitoloStudio;
    voto?: string;
}