/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AziAnagraficaBlp } from './aziAnagraficaBlp';
import { CondLavorativaOfferta } from './condLavorativaOfferta';
import { Fonte } from './fonte';
import { InformaticaRich } from './informaticaRich';
import { Intermediario } from './intermediario';
import { IscrizioneAlboRich } from './iscrizioneAlboRich';
import { IstruzioneRich } from './istruzioneRich';
import { LinguaRich } from './linguaRich';
import { MotivoChiusura } from './motivoChiusura';
import { MotivoChiusuraVacancy } from './motivoChiusuraVacancy';
import { ProfiloRicercato } from './profiloRicercato';
import { ServizioSpecialistico } from './servizioSpecialistico';
import { StatoComunicazione } from './statoComunicazione';
import { TipoAbilitazRich } from './tipoAbilitazRich';
import { TipoComunicazione } from './tipoComunicazione';
import { TipoPatenteRich } from './tipoPatenteRich';
import { VacancyManifestazione } from './vacancyManifestazione';
import { VacancyStato } from './vacancyStato';

export interface Vacancy { 
    annoAnnuncio?: number;
    codOfferta?: string;
    codOffertaIntermediario?: string;
    codOffertaPrec?: string;
    codStatoVacancy?: StatoComunicazione;
    codUserAggiorn?: string;
    codUserInserim?: string;
    codiceFiscaleReferente?: string;
    cognomeReferente?: string;
    condLavorativaOffertaList?: Array<CondLavorativaOfferta>;
    dAggiorn?: Date;
    dInserim?: Date;
    dInvio?: Date;
    dScadenza: Date;
    dsAltreConoscenzeCapacita?: string;
    dsRuoloReferente?: string;
    dsUlterioriRequisiti?: string;
    emailInvio: string;
    emailReferente?: string;
    flgL68Art1?: string;
    flgL68Art18?: string;
    flgMezzoProprio?: string;
    flgNullaOsta?: string;
    flgPubblicazioneClic?: string;
    flgSollecito?: string;
    flgTrasferte?: string;
    flgVisibilitaIntermediario?: string;
    id?: number;
    idAnnuncio?: string;
    idAziAnagrafica: AziAnagraficaBlp;
    idFonte: Fonte;
    idIntermediario?: Intermediario;
    idMotivoChiusura?: MotivoChiusura;
    idMotivoChiusuraVacancy?: MotivoChiusuraVacancy;
    idServizioSpecialistico?: ServizioSpecialistico;
    idTipoComunicazione?: TipoComunicazione;
    idVacancyPrec?: Vacancy;
    informaticaRichList?: Array<InformaticaRich>;
    iscrizioneAlboRichList?: Array<IscrizioneAlboRich>;
    istruzioneRichList?: Array<IstruzioneRich>;
    linguaRichList?: Array<LinguaRich>;
    nomeReferente?: string;
    numTelefonoReferente?: string;
    profiloRicercatoList?: Array<ProfiloRicercato>;
    testoCondizioniLavorative?: string;
    testoProfiloProfessionale?: string;
    testoRequisiti?: string;
    tipoAbilitazRichList?: Array<TipoAbilitazRich>;
    tipoPatenteRichList?: Array<TipoPatenteRich>;
    titoloVacancy: string;
    urlGoogleMaps?: string;
    vacancyManifestazioneList?: Array<VacancyManifestazione>;
    vacancyStatoList?: Array<VacancyStato>;
}