/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { ConsultaAnnunciRequest } from '../model/consultaAnnunciRequest';
import { ConsultaAnnunciResponse } from '../model/consultaAnnunciResponse';
import { DettaglioAnnuncioResponse } from '../model/dettaglioAnnuncioResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})

export class AnnunciPublicPslpService {


    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Restituisce gli annunci cercati
     * 
     * @param page 
     * @param body 
     * @param recForPage 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public consultaAnnunci1(page: number, body?: ConsultaAnnunciRequest, recForPage?: number, observe?: 'body', reportProgress?: boolean): Observable<ConsultaAnnunciResponse>;
    public consultaAnnunci1(page: number, body?: ConsultaAnnunciRequest, recForPage?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ConsultaAnnunciResponse>>;
    public consultaAnnunci1(page: number, body?: ConsultaAnnunciRequest, recForPage?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ConsultaAnnunciResponse>>;
    public consultaAnnunci1(page: number, body?: ConsultaAnnunciRequest, recForPage?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (page === null || page === undefined) {
            throw new Error('Required parameter page was null or undefined when calling consultaAnnunci1.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (recForPage !== undefined && recForPage !== null) {
            queryParameters = queryParameters.set('recForPage', <any>recForPage);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ConsultaAnnunciResponse>(`${this.basePath}/api-public/v1/annunci-pslp/consulta-annunci`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * dettaglio annuncio
     * 
     * @param idAnnuncio 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDettaglioAnnuncio1(idAnnuncio: number, observe?: 'body', reportProgress?: boolean): Observable<DettaglioAnnuncioResponse>;
    public getDettaglioAnnuncio1(idAnnuncio: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioAnnuncioResponse>>;
    public getDettaglioAnnuncio1(idAnnuncio: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioAnnuncioResponse>>;
    public getDettaglioAnnuncio1(idAnnuncio: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idAnnuncio === null || idAnnuncio === undefined) {
            throw new Error('Required parameter idAnnuncio was null or undefined when calling getDettaglioAnnuncio1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.post<DettaglioAnnuncioResponse>(`${this.basePath}/api-public/v1/annunci-pslp/get-dettaglio/${encodeURIComponent(String(idAnnuncio))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}

