/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { DecodificaListResponse } from '../model/decodificaListResponse';
import { DecodificaResponse } from '../model/decodificaResponse';
import { ParametroResponse } from '../model/parametroResponse';
import { TipoLavoroResponse } from '../model/tipoLavoroResponse';
import { TitoloStudioResponse } from '../model/titoloStudioResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})

export class DecodificaPslpService {


    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Restituisce comuni per provincia autocomplete
     * 
     * @param idProvincia 
     * @param txt 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public fillComuneByIdProvincia(idProvincia: string, txt: string, observe?: 'body', reportProgress?: boolean): Observable<DecodificaListResponse>;
    public fillComuneByIdProvincia(idProvincia: string, txt: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaListResponse>>;
    public fillComuneByIdProvincia(idProvincia: string, txt: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaListResponse>>;
    public fillComuneByIdProvincia(idProvincia: string, txt: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idProvincia === null || idProvincia === undefined) {
            throw new Error('Required parameter idProvincia was null or undefined when calling fillComuneByIdProvincia.');
        }

        if (txt === null || txt === undefined) {
            throw new Error('Required parameter txt was null or undefined when calling fillComuneByIdProvincia.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DecodificaListResponse>(`${this.basePath}/api/v1/decodifica-pslp/fill-comuneByIdProvincia/${encodeURIComponent(String(idProvincia))}/${encodeURIComponent(String(txt))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce elenco decodifiche di tipo autocomplete
     * 
     * @param tipo 
     * @param txt 
     * @param conCodice 
     * @param condizioneData 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public fillDecodificaByTipo(tipo: string, txt: string, conCodice?: string, condizioneData?: string, observe?: 'body', reportProgress?: boolean): Observable<DecodificaListResponse>;
    public fillDecodificaByTipo(tipo: string, txt: string, conCodice?: string, condizioneData?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaListResponse>>;
    public fillDecodificaByTipo(tipo: string, txt: string, conCodice?: string, condizioneData?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaListResponse>>;
    public fillDecodificaByTipo(tipo: string, txt: string, conCodice?: string, condizioneData?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tipo === null || tipo === undefined) {
            throw new Error('Required parameter tipo was null or undefined when calling fillDecodificaByTipo.');
        }

        if (txt === null || txt === undefined) {
            throw new Error('Required parameter txt was null or undefined when calling fillDecodificaByTipo.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (conCodice !== undefined && conCodice !== null) {
            queryParameters = queryParameters.set('conCodice', <any>conCodice);
        }
        if (condizioneData !== undefined && condizioneData !== null) {
            queryParameters = queryParameters.set('condizioneData', <any>condizioneData);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DecodificaListResponse>(`${this.basePath}/api/v1/decodifica-pslp/fill/${encodeURIComponent(String(tipo))}/${encodeURIComponent(String(txt))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce Elenco competenze informatiche dettagliate per idSilTInformatica
     * 
     * @param idInformatica 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public fillInformaticaDettByIdInformatica(idInformatica: number, observe?: 'body', reportProgress?: boolean): Observable<DecodificaListResponse>;
    public fillInformaticaDettByIdInformatica(idInformatica: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaListResponse>>;
    public fillInformaticaDettByIdInformatica(idInformatica: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaListResponse>>;
    public fillInformaticaDettByIdInformatica(idInformatica: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idInformatica === null || idInformatica === undefined) {
            throw new Error('Required parameter idInformatica was null or undefined when calling fillInformaticaDettByIdInformatica.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DecodificaListResponse>(`${this.basePath}/api/v1/decodifica-pslp/find-informaticaDettByIdInformatica/${encodeURIComponent(String(idInformatica))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce tutti i tipi responsabilita autocomplete
     * 
     * @param txt 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public fillTipoResponsabilita(txt: string, observe?: 'body', reportProgress?: boolean): Observable<Array<DecodificaResponse>>;
    public fillTipoResponsabilita(txt: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DecodificaResponse>>>;
    public fillTipoResponsabilita(txt: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DecodificaResponse>>>;
    public fillTipoResponsabilita(txt: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (txt === null || txt === undefined) {
            throw new Error('Required parameter txt was null or undefined when calling fillTipoResponsabilita.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<DecodificaResponse>>(`${this.basePath}/api/v1/decodifica-pslp/fill-tipo-responsabilita/${encodeURIComponent(String(txt))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce Elenco comuni per provincia
     * 
     * @param idProvincia 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findComuneByIdProvincia(idProvincia: string, observe?: 'body', reportProgress?: boolean): Observable<DecodificaListResponse>;
    public findComuneByIdProvincia(idProvincia: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaListResponse>>;
    public findComuneByIdProvincia(idProvincia: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaListResponse>>;
    public findComuneByIdProvincia(idProvincia: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idProvincia === null || idProvincia === undefined) {
            throw new Error('Required parameter idProvincia was null or undefined when calling findComuneByIdProvincia.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DecodificaListResponse>(`${this.basePath}/api/v1/decodifica-pslp/find-comuneByIdProvincia/${encodeURIComponent(String(idProvincia))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce Elenco decodifica in base al tipo di codifica passato come parametro
     * 
     * @param tipo 
     * @param condizioneData 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findDecodificaByTipo(tipo: string, condizioneData?: string, observe?: 'body', reportProgress?: boolean): Observable<DecodificaListResponse>;
    public findDecodificaByTipo(tipo: string, condizioneData?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaListResponse>>;
    public findDecodificaByTipo(tipo: string, condizioneData?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaListResponse>>;
    public findDecodificaByTipo(tipo: string, condizioneData?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tipo === null || tipo === undefined) {
            throw new Error('Required parameter tipo was null or undefined when calling findDecodificaByTipo.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (condizioneData !== undefined && condizioneData !== null) {
            queryParameters = queryParameters.set('condizioneData', <any>condizioneData);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DecodificaListResponse>(`${this.basePath}/api/v1/decodifica-pslp/find/${encodeURIComponent(String(tipo))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce Elenco decodifica in base al tipo e id di codifica passato come parametro
     * 
     * @param tipo 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findDecodificaByTipoEdId(tipo: string, id: string, observe?: 'body', reportProgress?: boolean): Observable<DecodificaResponse>;
    public findDecodificaByTipoEdId(tipo: string, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaResponse>>;
    public findDecodificaByTipoEdId(tipo: string, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaResponse>>;
    public findDecodificaByTipoEdId(tipo: string, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tipo === null || tipo === undefined) {
            throw new Error('Required parameter tipo was null or undefined when calling findDecodificaByTipoEdId.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling findDecodificaByTipoEdId.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DecodificaResponse>(`${this.basePath}/api/v1/decodifica-pslp/find-tipo-id/${encodeURIComponent(String(tipo))}/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce il parametro dato il codice
     * 
     * @param cod 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findParametro(cod: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ParametroResponse>>;
    public findParametro(cod: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ParametroResponse>>>;
    public findParametro(cod: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ParametroResponse>>>;
    public findParametro(cod: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cod === null || cod === undefined) {
            throw new Error('Required parameter cod was null or undefined when calling findParametro.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ParametroResponse>>(`${this.basePath}/api/v1/decodifica-pslp/find-parametro/${encodeURIComponent(String(cod))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce il dettaglio del titolo di studio
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findTipoLavoro(id: string, observe?: 'body', reportProgress?: boolean): Observable<TipoLavoroResponse>;
    public findTipoLavoro(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TipoLavoroResponse>>;
    public findTipoLavoro(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TipoLavoroResponse>>;
    public findTipoLavoro(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling findTipoLavoro.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<TipoLavoroResponse>(`${this.basePath}/api/v1/decodifica-pslp/find-tipo-lavoro/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce tutti i tipi responsabilita
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findTipoResponsabilita(observe?: 'body', reportProgress?: boolean): Observable<Array<DecodificaResponse>>;
    public findTipoResponsabilita(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DecodificaResponse>>>;
    public findTipoResponsabilita(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DecodificaResponse>>>;
    public findTipoResponsabilita(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<DecodificaResponse>>(`${this.basePath}/api/v1/decodifica-pslp/find-tipo-responsabilita`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce il tipo responsabilita
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findTipoResponsabilitaById(id: string, observe?: 'body', reportProgress?: boolean): Observable<DecodificaResponse>;
    public findTipoResponsabilitaById(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaResponse>>;
    public findTipoResponsabilitaById(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaResponse>>;
    public findTipoResponsabilitaById(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling findTipoResponsabilitaById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DecodificaResponse>(`${this.basePath}/api/v1/decodifica-pslp/find-tipo-responsabilita/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce il dettaglio del titolo di studio
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findTitoloStudioById(id: string, observe?: 'body', reportProgress?: boolean): Observable<TitoloStudioResponse>;
    public findTitoloStudioById(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TitoloStudioResponse>>;
    public findTitoloStudioById(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TitoloStudioResponse>>;
    public findTitoloStudioById(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling findTitoloStudioById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<TitoloStudioResponse>(`${this.basePath}/api/v1/decodifica-pslp/find-titoloStudioById/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce tutti i parametri
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findTuttiParametro(observe?: 'body', reportProgress?: boolean): Observable<Array<ParametroResponse>>;
    public findTuttiParametro(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ParametroResponse>>>;
    public findTuttiParametro(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ParametroResponse>>>;
    public findTuttiParametro(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ParametroResponse>>(`${this.basePath}/api/v1/decodifica-pslp/find-parametro`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}

