/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { CommonRequest } from '../model/commonRequest';
import { DecodificaListResponse } from '../model/decodificaListResponse';
import { DecodificaResponse } from '../model/decodificaResponse';
import { PslpMessaggio } from '../model/pslpMessaggio';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})

export class DecodificaPublicPslpService {


    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Restituisce tutte decodifiche per tipo
     * 
     * @param tipo 
     * @param txt 
     * @param body 
     * @param conCodice 
     * @param condizioneData 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public fill1(tipo: string, txt: string, body?: CommonRequest, conCodice?: string, condizioneData?: string, observe?: 'body', reportProgress?: boolean): Observable<DecodificaListResponse>;
    public fill1(tipo: string, txt: string, body?: CommonRequest, conCodice?: string, condizioneData?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaListResponse>>;
    public fill1(tipo: string, txt: string, body?: CommonRequest, conCodice?: string, condizioneData?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaListResponse>>;
    public fill1(tipo: string, txt: string, body?: CommonRequest, conCodice?: string, condizioneData?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tipo === null || tipo === undefined) {
            throw new Error('Required parameter tipo was null or undefined when calling fill1.');
        }

        if (txt === null || txt === undefined) {
            throw new Error('Required parameter txt was null or undefined when calling fill1.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (conCodice !== undefined && conCodice !== null) {
            queryParameters = queryParameters.set('conCodice', <any>conCodice);
        }
        if (condizioneData !== undefined && condizioneData !== null) {
            queryParameters = queryParameters.set('condizioneData', <any>condizioneData);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DecodificaListResponse>(`${this.basePath}/api-public/v1/decodifica-pslp/fill/${encodeURIComponent(String(tipo))}/${encodeURIComponent(String(txt))}`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce il messaggio
     * 
     * @param cod 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findByCodPublic(cod: string, observe?: 'body', reportProgress?: boolean): Observable<PslpMessaggio>;
    public findByCodPublic(cod: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PslpMessaggio>>;
    public findByCodPublic(cod: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PslpMessaggio>>;
    public findByCodPublic(cod: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cod === null || cod === undefined) {
            throw new Error('Required parameter cod was null or undefined when calling findByCodPublic.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PslpMessaggio>(`${this.basePath}/api-public/v1/decodifica-pslp/messaggio/${encodeURIComponent(String(cod))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce la decodifica per tipo e id
     * 
     * @param tipo 
     * @param id 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findDecodificaBlpById1(tipo: string, id: string, body?: CommonRequest, observe?: 'body', reportProgress?: boolean): Observable<DecodificaResponse>;
    public findDecodificaBlpById1(tipo: string, id: string, body?: CommonRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaResponse>>;
    public findDecodificaBlpById1(tipo: string, id: string, body?: CommonRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaResponse>>;
    public findDecodificaBlpById1(tipo: string, id: string, body?: CommonRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tipo === null || tipo === undefined) {
            throw new Error('Required parameter tipo was null or undefined when calling findDecodificaBlpById1.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling findDecodificaBlpById1.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DecodificaResponse>(`${this.basePath}/api-public/v1/decodifica-pslp/find/${encodeURIComponent(String(tipo))}/${encodeURIComponent(String(id))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce tutte decodifiche per tipo
     * 
     * @param tipo 
     * @param body 
     * @param condizioneData 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findDecodificaBlpByTipo1(tipo: string, body?: CommonRequest, condizioneData?: string, observe?: 'body', reportProgress?: boolean): Observable<DecodificaListResponse>;
    public findDecodificaBlpByTipo1(tipo: string, body?: CommonRequest, condizioneData?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DecodificaListResponse>>;
    public findDecodificaBlpByTipo1(tipo: string, body?: CommonRequest, condizioneData?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DecodificaListResponse>>;
    public findDecodificaBlpByTipo1(tipo: string, body?: CommonRequest, condizioneData?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tipo === null || tipo === undefined) {
            throw new Error('Required parameter tipo was null or undefined when calling findDecodificaBlpByTipo1.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (condizioneData !== undefined && condizioneData !== null) {
            queryParameters = queryParameters.set('condizioneData', <any>condizioneData);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DecodificaListResponse>(`${this.basePath}/api-public/v1/decodifica-pslp/find/${encodeURIComponent(String(tipo))}`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce tutte le funzioni
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findFunzione(observe?: 'body', reportProgress?: boolean): Observable<Array<DecodificaResponse>>;
    public findFunzione(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DecodificaResponse>>>;
    public findFunzione(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DecodificaResponse>>>;
    public findFunzione(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<DecodificaResponse>>(`${this.basePath}/api-public/v1/decodifica-pslp/find-funzione`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce tutte le funzioni
     * 
     * @param idRuolo 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findFunzioneByIdruolo(idRuolo: number, observe?: 'body', reportProgress?: boolean): Observable<Array<DecodificaResponse>>;
    public findFunzioneByIdruolo(idRuolo: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DecodificaResponse>>>;
    public findFunzioneByIdruolo(idRuolo: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DecodificaResponse>>>;
    public findFunzioneByIdruolo(idRuolo: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idRuolo === null || idRuolo === undefined) {
            throw new Error('Required parameter idRuolo was null or undefined when calling findFunzioneByIdruolo.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<DecodificaResponse>>(`${this.basePath}/api-public/v1/decodifica-pslp/find-funzione-by-idruolo/${encodeURIComponent(String(idRuolo))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}

