/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { DelegaListResponse } from '../model/delegaListResponse';
import { DelegaResponse } from '../model/delegaResponse';
import { FormAnagraficaLav } from '../model/formAnagraficaLav';
import { MsgResponse } from '../model/msgResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})

export class DelegaService {


    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * attiva delega 
     * 
     * @param idDelega 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public attivaDelega(idDelega: number, observe?: 'body', reportProgress?: boolean): Observable<MsgResponse>;
    public attivaDelega(idDelega: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MsgResponse>>;
    public attivaDelega(idDelega: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MsgResponse>>;
    public attivaDelega(idDelega: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idDelega === null || idDelega === undefined) {
            throw new Error('Required parameter idDelega was null or undefined when calling attivaDelega.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.post<MsgResponse>(`${this.basePath}/api/v1/delega/attiva-delega/${encodeURIComponent(String(idDelega))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Cancella delega 
     * 
     * @param idDelega 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cancellaDelega(idDelega: number, observe?: 'body', reportProgress?: boolean): Observable<MsgResponse>;
    public cancellaDelega(idDelega: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MsgResponse>>;
    public cancellaDelega(idDelega: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MsgResponse>>;
    public cancellaDelega(idDelega: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idDelega === null || idDelega === undefined) {
            throw new Error('Required parameter idDelega was null or undefined when calling cancellaDelega.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<MsgResponse>(`${this.basePath}/api/v1/delega/cancella-delega/${encodeURIComponent(String(idDelega))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce l&#x27;elenco dei deleganti passando come parametro l&#x27;id del delegati
     * 
     * @param idUtenteDelegante 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findDelegheByDelegante(idUtenteDelegante: number, observe?: 'body', reportProgress?: boolean): Observable<Array<DelegaListResponse>>;
    public findDelegheByDelegante(idUtenteDelegante: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DelegaListResponse>>>;
    public findDelegheByDelegante(idUtenteDelegante: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DelegaListResponse>>>;
    public findDelegheByDelegante(idUtenteDelegante: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idUtenteDelegante === null || idUtenteDelegante === undefined) {
            throw new Error('Required parameter idUtenteDelegante was null or undefined when calling findDelegheByDelegante.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<DelegaListResponse>>(`${this.basePath}/api/v1/delega/by-delegante/${encodeURIComponent(String(idUtenteDelegante))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce l&#x27;elenco dei delegati passando come parametro l&#x27;id del deleganti
     * 
     * @param idUtenteDelegto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findDelegheByDelegate(idUtenteDelegto: number, observe?: 'body', reportProgress?: boolean): Observable<Array<DelegaListResponse>>;
    public findDelegheByDelegate(idUtenteDelegto: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DelegaListResponse>>>;
    public findDelegheByDelegate(idUtenteDelegto: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DelegaListResponse>>>;
    public findDelegheByDelegate(idUtenteDelegto: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idUtenteDelegto === null || idUtenteDelegto === undefined) {
            throw new Error('Required parameter idUtenteDelegto was null or undefined when calling findDelegheByDelegate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<DelegaListResponse>>(`${this.basePath}/api/v1/delega/by-delegato/${encodeURIComponent(String(idUtenteDelegto))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Salva delega 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertDelega(body?: FormAnagraficaLav, observe?: 'body', reportProgress?: boolean): Observable<DelegaResponse>;
    public insertDelega(body?: FormAnagraficaLav, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DelegaResponse>>;
    public insertDelega(body?: FormAnagraficaLav, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DelegaResponse>>;
    public insertDelega(body?: FormAnagraficaLav, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DelegaResponse>(`${this.basePath}/api/v1/delega/salva-delega`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Invio codice otp 
     * 
     * @param cf 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public invioCodiceOtp(cf: string, observe?: 'body', reportProgress?: boolean): Observable<MsgResponse>;
    public invioCodiceOtp(cf: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MsgResponse>>;
    public invioCodiceOtp(cf: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MsgResponse>>;
    public invioCodiceOtp(cf: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cf === null || cf === undefined) {
            throw new Error('Required parameter cf was null or undefined when calling invioCodiceOtp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.post<MsgResponse>(`${this.basePath}/api/v1/delega/invio-codice-otp/${encodeURIComponent(String(cf))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Verifica codice otp 
     * 
     * @param cf 
     * @param otp 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public verificaCodiceOtp(cf: string, otp: number, observe?: 'body', reportProgress?: boolean): Observable<MsgResponse>;
    public verificaCodiceOtp(cf: string, otp: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MsgResponse>>;
    public verificaCodiceOtp(cf: string, otp: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MsgResponse>>;
    public verificaCodiceOtp(cf: string, otp: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cf === null || cf === undefined) {
            throw new Error('Required parameter cf was null or undefined when calling verificaCodiceOtp.');
        }

        if (otp === null || otp === undefined) {
            throw new Error('Required parameter otp was null or undefined when calling verificaCodiceOtp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.post<MsgResponse>(`${this.basePath}/api/v1/delega/verifica-codice-otp/${encodeURIComponent(String(cf))}/${encodeURIComponent(String(otp))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}

