/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { DocumentoRichiestoResponse } from '../model/documentoRichiestoResponse';
import { FormRicercaRichiesteDocumenti } from '../model/formRicercaRichiesteDocumenti';
import { InserisciAggiornaRichiestaDocumentoRequest } from '../model/inserisciAggiornaRichiestaDocumentoRequest';
import { RicercaRichiesteDocumentiResponse } from '../model/ricercaRichiesteDocumentiResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})

export class DocumentiService {


    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Aggiorna stato richiesta documento
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inserisciRichiestaDocumento(body?: InserisciAggiornaRichiestaDocumentoRequest, observe?: 'body', reportProgress?: boolean): Observable<DocumentoRichiestoResponse>;
    public inserisciRichiestaDocumento(body?: InserisciAggiornaRichiestaDocumentoRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DocumentoRichiestoResponse>>;
    public inserisciRichiestaDocumento(body?: InserisciAggiornaRichiestaDocumentoRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DocumentoRichiestoResponse>>;
    public inserisciRichiestaDocumento(body?: InserisciAggiornaRichiestaDocumentoRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DocumentoRichiestoResponse>(`${this.basePath}/api/v1/documenti/inserisci-richiesta-documento`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce l&#x27;elenco delle richieste documenti
     * 
     * @param page 
     * @param body 
     * @param recForPage 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public ricercaRichiesteDocumenti(page: number, body?: FormRicercaRichiesteDocumenti, recForPage?: number, observe?: 'body', reportProgress?: boolean): Observable<RicercaRichiesteDocumentiResponse>;
    public ricercaRichiesteDocumenti(page: number, body?: FormRicercaRichiesteDocumenti, recForPage?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RicercaRichiesteDocumentiResponse>>;
    public ricercaRichiesteDocumenti(page: number, body?: FormRicercaRichiesteDocumenti, recForPage?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RicercaRichiesteDocumentiResponse>>;
    public ricercaRichiesteDocumenti(page: number, body?: FormRicercaRichiesteDocumenti, recForPage?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (page === null || page === undefined) {
            throw new Error('Required parameter page was null or undefined when calling ricercaRichiesteDocumenti.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (recForPage !== undefined && recForPage !== null) {
            queryParameters = queryParameters.set('recForPage', <any>recForPage);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<RicercaRichiesteDocumentiResponse>(`${this.basePath}/api/v1/documenti/ricerca-richieste-documenti`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Stampa documento richiesto
     * 
     * @param idRichiestaDocumento 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public stampaDocumentoRichiesto(idRichiestaDocumento: number, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public stampaDocumentoRichiesto(idRichiestaDocumento: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public stampaDocumentoRichiesto(idRichiestaDocumento: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public stampaDocumentoRichiesto(idRichiestaDocumento: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idRichiestaDocumento === null || idRichiestaDocumento === undefined) {
            throw new Error('Required parameter idRichiestaDocumento was null or undefined when calling stampaDocumentoRichiesto.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/pdf'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Blob>(`${this.basePath}/api/v1/documenti/stampa-documento-richiesto/${encodeURIComponent(String(idRichiestaDocumento))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Visualizza richiesta documento
     * 
     * @param idRichiestaDocumento 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public visualizzaRichiestaDocumento(idRichiestaDocumento: number, observe?: 'body', reportProgress?: boolean): Observable<DocumentoRichiestoResponse>;
    public visualizzaRichiestaDocumento(idRichiestaDocumento: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DocumentoRichiestoResponse>>;
    public visualizzaRichiestaDocumento(idRichiestaDocumento: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DocumentoRichiestoResponse>>;
    public visualizzaRichiestaDocumento(idRichiestaDocumento: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idRichiestaDocumento === null || idRichiestaDocumento === undefined) {
            throw new Error('Required parameter idRichiestaDocumento was null or undefined when calling visualizzaRichiestaDocumento.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DocumentoRichiestoResponse>(`${this.basePath}/api/v1/documenti/visualizza-richiesta-documento/${encodeURIComponent(String(idRichiestaDocumento))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}

