/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AlboRequest } from '../model/alboRequest';
import { AlboResponse } from '../model/alboResponse';
import { ApiError } from '../model/apiError';
import { ControlliFascicoloRequest } from '../model/controlliFascicoloRequest';
import { ControlliFascicoloResponse } from '../model/controlliFascicoloResponse';
import { CorsoFormazioneRequest } from '../model/corsoFormazioneRequest';
import { CorsoFormazioneResponse } from '../model/corsoFormazioneResponse';
import { DettaglioCorsoFormazioneResponse } from '../model/dettaglioCorsoFormazioneResponse';
import { DettaglioEsperienzeProfessionaliResponse } from '../model/dettaglioEsperienzeProfessionaliResponse';
import { DettaglioFascicoloResponse } from '../model/dettaglioFascicoloResponse';
import { DettaglioTitoloDiStudioResponse } from '../model/dettaglioTitoloDiStudioResponse';
import { EsperienzaLavoroRequest } from '../model/esperienzaLavoroRequest';
import { EsperienzaLavoroResponse } from '../model/esperienzaLavoroResponse';
import { InformaticaRequest } from '../model/informaticaRequest';
import { InformaticaResponse } from '../model/informaticaResponse';
import { LinguaRequest } from '../model/linguaRequest';
import { LinguaResponse } from '../model/linguaResponse';
import { MsgResponse } from '../model/msgResponse';
import { PatenteRequest } from '../model/patenteRequest';
import { PatenteResponse } from '../model/patenteResponse';
import { RicercaSediAziendaRequest } from '../model/ricercaSediAziendaRequest';
import { RicercaSediAziendaResponse } from '../model/ricercaSediAziendaResponse';
import { TitoloStudioLavoratoreResponse } from '../model/titoloStudioLavoratoreResponse';
import { TitoloStudioRequest } from '../model/titoloStudioRequest';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})

export class FascicoloPslpService {


    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * controlli inserimento modifica e salvataggio
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllaProseguiSalva(body?: ControlliFascicoloRequest, observe?: 'body', reportProgress?: boolean): Observable<ControlliFascicoloResponse>;
    public controllaProseguiSalva(body?: ControlliFascicoloRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ControlliFascicoloResponse>>;
    public controllaProseguiSalva(body?: ControlliFascicoloRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ControlliFascicoloResponse>>;
    public controllaProseguiSalva(body?: ControlliFascicoloRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ControlliFascicoloResponse>(`${this.basePath}/api/v1/fascicolo-pslp/controlla-prosegui-salva`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Cancella il corso o la qualifica selezionato
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCorsoFormazione(body?: CorsoFormazioneRequest, observe?: 'body', reportProgress?: boolean): Observable<MsgResponse>;
    public deleteCorsoFormazione(body?: CorsoFormazioneRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MsgResponse>>;
    public deleteCorsoFormazione(body?: CorsoFormazioneRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MsgResponse>>;
    public deleteCorsoFormazione(body?: CorsoFormazioneRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MsgResponse>(`${this.basePath}/api/v1/fascicolo-pslp/delete-corso-formazione`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Cancella l&#x27;esperienza lavorativa
     * 
     * @param idSilLavEsperienzaLavoro 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteEsperienzaProfessionale(idSilLavEsperienzaLavoro: number, observe?: 'body', reportProgress?: boolean): Observable<MsgResponse>;
    public deleteEsperienzaProfessionale(idSilLavEsperienzaLavoro: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MsgResponse>>;
    public deleteEsperienzaProfessionale(idSilLavEsperienzaLavoro: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MsgResponse>>;
    public deleteEsperienzaProfessionale(idSilLavEsperienzaLavoro: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSilLavEsperienzaLavoro === null || idSilLavEsperienzaLavoro === undefined) {
            throw new Error('Required parameter idSilLavEsperienzaLavoro was null or undefined when calling deleteEsperienzaProfessionale.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<MsgResponse>(`${this.basePath}/api/v1/fascicolo-pslp/delete-esperienza-lavoro/${encodeURIComponent(String(idSilLavEsperienzaLavoro))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Cancella la informatica selezionata
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteInformatica(body?: InformaticaRequest, observe?: 'body', reportProgress?: boolean): Observable<MsgResponse>;
    public deleteInformatica(body?: InformaticaRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MsgResponse>>;
    public deleteInformatica(body?: InformaticaRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MsgResponse>>;
    public deleteInformatica(body?: InformaticaRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MsgResponse>(`${this.basePath}/api/v1/fascicolo-pslp/delete-informatica`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Cancella la lingua selezionata
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteLingua(body?: LinguaRequest, observe?: 'body', reportProgress?: boolean): Observable<MsgResponse>;
    public deleteLingua(body?: LinguaRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MsgResponse>>;
    public deleteLingua(body?: LinguaRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MsgResponse>>;
    public deleteLingua(body?: LinguaRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MsgResponse>(`${this.basePath}/api/v1/fascicolo-pslp/delete-lingua`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Cancella il titolo di studio
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteTitoloStudio(body?: TitoloStudioRequest, observe?: 'body', reportProgress?: boolean): Observable<MsgResponse>;
    public deleteTitoloStudio(body?: TitoloStudioRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MsgResponse>>;
    public deleteTitoloStudio(body?: TitoloStudioRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MsgResponse>>;
    public deleteTitoloStudio(body?: TitoloStudioRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MsgResponse>(`${this.basePath}/api/v1/fascicolo-pslp/delete-titolo-studio`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * dettaglio corso formazione
     * 
     * @param idSilLavCorsoForm 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDettaglioCorsoFormazione(idSilLavCorsoForm: number, observe?: 'body', reportProgress?: boolean): Observable<DettaglioCorsoFormazioneResponse>;
    public getDettaglioCorsoFormazione(idSilLavCorsoForm: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioCorsoFormazioneResponse>>;
    public getDettaglioCorsoFormazione(idSilLavCorsoForm: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioCorsoFormazioneResponse>>;
    public getDettaglioCorsoFormazione(idSilLavCorsoForm: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSilLavCorsoForm === null || idSilLavCorsoForm === undefined) {
            throw new Error('Required parameter idSilLavCorsoForm was null or undefined when calling getDettaglioCorsoFormazione.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DettaglioCorsoFormazioneResponse>(`${this.basePath}/api/v1/fascicolo-pslp/get-dettaglio-corso-formazione/${encodeURIComponent(String(idSilLavCorsoForm))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * dettaglio esperienza professionale
     * 
     * @param idSilLavEsperienzaLavoro 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDettaglioEsperienzaProfessionale(idSilLavEsperienzaLavoro: number, observe?: 'body', reportProgress?: boolean): Observable<DettaglioEsperienzeProfessionaliResponse>;
    public getDettaglioEsperienzaProfessionale(idSilLavEsperienzaLavoro: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioEsperienzeProfessionaliResponse>>;
    public getDettaglioEsperienzaProfessionale(idSilLavEsperienzaLavoro: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioEsperienzeProfessionaliResponse>>;
    public getDettaglioEsperienzaProfessionale(idSilLavEsperienzaLavoro: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSilLavEsperienzaLavoro === null || idSilLavEsperienzaLavoro === undefined) {
            throw new Error('Required parameter idSilLavEsperienzaLavoro was null or undefined when calling getDettaglioEsperienzaProfessionale.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DettaglioEsperienzeProfessionaliResponse>(`${this.basePath}/api/v1/fascicolo-pslp/get-dettaglio-esperienza-professionale/${encodeURIComponent(String(idSilLavEsperienzaLavoro))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce dettaglio scheda anagrafica professionale
     * 
     * @param idSilLavAnagrafica 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDettaglioFascicolo(idSilLavAnagrafica: number, observe?: 'body', reportProgress?: boolean): Observable<DettaglioFascicoloResponse>;
    public getDettaglioFascicolo(idSilLavAnagrafica: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioFascicoloResponse>>;
    public getDettaglioFascicolo(idSilLavAnagrafica: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioFascicoloResponse>>;
    public getDettaglioFascicolo(idSilLavAnagrafica: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSilLavAnagrafica === null || idSilLavAnagrafica === undefined) {
            throw new Error('Required parameter idSilLavAnagrafica was null or undefined when calling getDettaglioFascicolo.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DettaglioFascicoloResponse>(`${this.basePath}/api/v1/fascicolo-pslp/get-dettaglio/${encodeURIComponent(String(idSilLavAnagrafica))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * dettaglio titolo di studio
     * 
     * @param idSilLavTitoloStudio 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDettaglioTitoloDiStudio(idSilLavTitoloStudio: number, observe?: 'body', reportProgress?: boolean): Observable<DettaglioTitoloDiStudioResponse>;
    public getDettaglioTitoloDiStudio(idSilLavTitoloStudio: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioTitoloDiStudioResponse>>;
    public getDettaglioTitoloDiStudio(idSilLavTitoloStudio: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioTitoloDiStudioResponse>>;
    public getDettaglioTitoloDiStudio(idSilLavTitoloStudio: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSilLavTitoloStudio === null || idSilLavTitoloStudio === undefined) {
            throw new Error('Required parameter idSilLavTitoloStudio was null or undefined when calling getDettaglioTitoloDiStudio.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DettaglioTitoloDiStudioResponse>(`${this.basePath}/api/v1/fascicolo-pslp/get-dettaglio-titolo-di-studio/${encodeURIComponent(String(idSilLavTitoloStudio))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * controlli inserimento e modifica e salvataggio tutto in uno
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inserisciModificaFascicoloCittadino(body?: ControlliFascicoloRequest, observe?: 'body', reportProgress?: boolean): Observable<ControlliFascicoloResponse>;
    public inserisciModificaFascicoloCittadino(body?: ControlliFascicoloRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ControlliFascicoloResponse>>;
    public inserisciModificaFascicoloCittadino(body?: ControlliFascicoloRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ControlliFascicoloResponse>>;
    public inserisciModificaFascicoloCittadino(body?: ControlliFascicoloRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ControlliFascicoloResponse>(`${this.basePath}/api/v1/fascicolo-pslp/inserisci-modifica-fascicolo-cittadino`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce o cancella l&#x27;albo
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertOrDeleteAlbo(body?: AlboRequest, observe?: 'body', reportProgress?: boolean): Observable<AlboResponse>;
    public insertOrDeleteAlbo(body?: AlboRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AlboResponse>>;
    public insertOrDeleteAlbo(body?: AlboRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AlboResponse>>;
    public insertOrDeleteAlbo(body?: AlboRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<AlboResponse>(`${this.basePath}/api/v1/fascicolo-pslp/insert-or-delete-albo`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce o aggiorna la tabella patenti
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertOrDeletePatente(body?: PatenteRequest, observe?: 'body', reportProgress?: boolean): Observable<PatenteResponse>;
    public insertOrDeletePatente(body?: PatenteRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PatenteResponse>>;
    public insertOrDeletePatente(body?: PatenteRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PatenteResponse>>;
    public insertOrDeletePatente(body?: PatenteRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PatenteResponse>(`${this.basePath}/api/v1/fascicolo-pslp/insert-or-delete-patente`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce o aggiorna il corso di formazione o qualifica
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertOrUpdateCorsoFormazione(body?: CorsoFormazioneRequest, observe?: 'body', reportProgress?: boolean): Observable<CorsoFormazioneResponse>;
    public insertOrUpdateCorsoFormazione(body?: CorsoFormazioneRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CorsoFormazioneResponse>>;
    public insertOrUpdateCorsoFormazione(body?: CorsoFormazioneRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CorsoFormazioneResponse>>;
    public insertOrUpdateCorsoFormazione(body?: CorsoFormazioneRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<CorsoFormazioneResponse>(`${this.basePath}/api/v1/fascicolo-pslp/insert-or-update-corso-formazione`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce o aggiorna l&#x27;esperienza lavorativa
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertOrUpdateEsperienzaLavoro(body?: EsperienzaLavoroRequest, observe?: 'body', reportProgress?: boolean): Observable<EsperienzaLavoroResponse>;
    public insertOrUpdateEsperienzaLavoro(body?: EsperienzaLavoroRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EsperienzaLavoroResponse>>;
    public insertOrUpdateEsperienzaLavoro(body?: EsperienzaLavoroRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EsperienzaLavoroResponse>>;
    public insertOrUpdateEsperienzaLavoro(body?: EsperienzaLavoroRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<EsperienzaLavoroResponse>(`${this.basePath}/api/v1/fascicolo-pslp/insert-or-update-esperienza-lavoro`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce o aggiorna la tabella informatica
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertOrUpdateInformatica(body?: InformaticaRequest, observe?: 'body', reportProgress?: boolean): Observable<InformaticaResponse>;
    public insertOrUpdateInformatica(body?: InformaticaRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InformaticaResponse>>;
    public insertOrUpdateInformatica(body?: InformaticaRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InformaticaResponse>>;
    public insertOrUpdateInformatica(body?: InformaticaRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<InformaticaResponse>(`${this.basePath}/api/v1/fascicolo-pslp/insert-or-update-informatica`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce o aggiorna la lingua
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertOrUpdateLingua(body?: LinguaRequest, observe?: 'body', reportProgress?: boolean): Observable<LinguaResponse>;
    public insertOrUpdateLingua(body?: LinguaRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LinguaResponse>>;
    public insertOrUpdateLingua(body?: LinguaRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LinguaResponse>>;
    public insertOrUpdateLingua(body?: LinguaRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<LinguaResponse>(`${this.basePath}/api/v1/fascicolo-pslp/insert-or-update-lingua`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce o aggiorna il titolo di studio
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertOrUpdateTitoloStudio(body?: TitoloStudioRequest, observe?: 'body', reportProgress?: boolean): Observable<TitoloStudioLavoratoreResponse>;
    public insertOrUpdateTitoloStudio(body?: TitoloStudioRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TitoloStudioLavoratoreResponse>>;
    public insertOrUpdateTitoloStudio(body?: TitoloStudioRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TitoloStudioLavoratoreResponse>>;
    public insertOrUpdateTitoloStudio(body?: TitoloStudioRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<TitoloStudioLavoratoreResponse>(`${this.basePath}/api/v1/fascicolo-pslp/insert-or-update-titolo-studio`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Ricerca azienda con sede
     * 
     * @param page 
     * @param body 
     * @param recForPage 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public ricercaSediAzienda(page: number, body?: RicercaSediAziendaRequest, recForPage?: number, observe?: 'body', reportProgress?: boolean): Observable<RicercaSediAziendaResponse>;
    public ricercaSediAzienda(page: number, body?: RicercaSediAziendaRequest, recForPage?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RicercaSediAziendaResponse>>;
    public ricercaSediAzienda(page: number, body?: RicercaSediAziendaRequest, recForPage?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RicercaSediAziendaResponse>>;
    public ricercaSediAzienda(page: number, body?: RicercaSediAziendaRequest, recForPage?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (page === null || page === undefined) {
            throw new Error('Required parameter page was null or undefined when calling ricercaSediAzienda.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (recForPage !== undefined && recForPage !== null) {
            queryParameters = queryParameters.set('recForPage', <any>recForPage);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<RicercaSediAziendaResponse>(`${this.basePath}/api/v1/fascicolo-pslp/ricerca-sedi-azienda`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}

