/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { CommonRequest } from '../model/commonRequest';
import { DettaglioAlboDichiaratoResponse } from '../model/dettaglioAlboDichiaratoResponse';
import { DettaglioAnagraficaResponse } from '../model/dettaglioAnagraficaResponse';
import { DettaglioConoscenzaInformaticaResponse } from '../model/dettaglioConoscenzaInformaticaResponse';
import { DettaglioCorsoFormazioneBlpResponse } from '../model/dettaglioCorsoFormazioneBlpResponse';
import { DettaglioEsperienzaDiLavoroResponse } from '../model/dettaglioEsperienzaDiLavoroResponse';
import { DettaglioIstruzioneDichResponse } from '../model/dettaglioIstruzioneDichResponse';
import { DettaglioLinguaConosciutaResponse } from '../model/dettaglioLinguaConosciutaResponse';
import { DettaglioPatentePossedutaResponse } from '../model/dettaglioPatentePossedutaResponse';
import { DettaglioPatentinoPossedutoResponse } from '../model/dettaglioPatentinoPossedutoResponse';
import { GeneraCvRequest } from '../model/generaCvRequest';
import { MapSilpToBlpAlbiRequest } from '../model/mapSilpToBlpAlbiRequest';
import { MapSilpToBlpConoscInformaticaRequest } from '../model/mapSilpToBlpConoscInformaticaRequest';
import { MapSilpToBlpEsperienzaLavRequest } from '../model/mapSilpToBlpEsperienzaLavRequest';
import { MapSilpToBlpFormazioneRequest } from '../model/mapSilpToBlpFormazioneRequest';
import { MapSilpToBlpIstruzioneRequest } from '../model/mapSilpToBlpIstruzioneRequest';
import { MapSilpToBlpLinguaRequest } from '../model/mapSilpToBlpLinguaRequest';
import { MapSilpToBlpPatenteRequest } from '../model/mapSilpToBlpPatenteRequest';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})

export class MappingService {


    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Restituisce l&#x27;anagrafica di blp
     * 
     * @param body 
     * @param idSilTAnagrafica 
     * @param idBlpLavAnagrafica 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public aggiornaAnagrafica(body: CommonRequest, idSilTAnagrafica?: number, idBlpLavAnagrafica?: number, observe?: 'body', reportProgress?: boolean): Observable<DettaglioAnagraficaResponse>;
    public aggiornaAnagrafica(body: CommonRequest, idSilTAnagrafica?: number, idBlpLavAnagrafica?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioAnagraficaResponse>>;
    public aggiornaAnagrafica(body: CommonRequest, idSilTAnagrafica?: number, idBlpLavAnagrafica?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioAnagraficaResponse>>;
    public aggiornaAnagrafica(body: CommonRequest, idSilTAnagrafica?: number, idBlpLavAnagrafica?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling aggiornaAnagrafica.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idSilTAnagrafica !== undefined && idSilTAnagrafica !== null) {
            queryParameters = queryParameters.set('idSilTAnagrafica', <any>idSilTAnagrafica);
        }
        if (idBlpLavAnagrafica !== undefined && idBlpLavAnagrafica !== null) {
            queryParameters = queryParameters.set('idBlpLavAnagrafica', <any>idBlpLavAnagrafica);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<DettaglioAnagraficaResponse>(`${this.basePath}/api/v1/map-silp-to-blp/blp-lav-anagrafica/update`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce l&#x27;anagrafica di blp
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAnagraficaByIdSilpAnag(body: GeneraCvRequest, observe?: 'body', reportProgress?: boolean): Observable<DettaglioAnagraficaResponse>;
    public getAnagraficaByIdSilpAnag(body: GeneraCvRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioAnagraficaResponse>>;
    public getAnagraficaByIdSilpAnag(body: GeneraCvRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioAnagraficaResponse>>;
    public getAnagraficaByIdSilpAnag(body: GeneraCvRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getAnagraficaByIdSilpAnag.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DettaglioAnagraficaResponse>(`${this.basePath}/api/v1/map-silp-to-blp/blp-lav-anagrafica`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce l&#x27;albo inserito
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertAlboFromSilp(body: MapSilpToBlpAlbiRequest, observe?: 'body', reportProgress?: boolean): Observable<DettaglioAlboDichiaratoResponse>;
    public insertAlboFromSilp(body: MapSilpToBlpAlbiRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioAlboDichiaratoResponse>>;
    public insertAlboFromSilp(body: MapSilpToBlpAlbiRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioAlboDichiaratoResponse>>;
    public insertAlboFromSilp(body: MapSilpToBlpAlbiRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertAlboFromSilp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DettaglioAlboDichiaratoResponse>(`${this.basePath}/api/v1/map-silp-to-blp/insert-albo`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce la conoscenza informatica inserito
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertConoscenzaInformaticaFromSilp(body: MapSilpToBlpConoscInformaticaRequest, observe?: 'body', reportProgress?: boolean): Observable<DettaglioConoscenzaInformaticaResponse>;
    public insertConoscenzaInformaticaFromSilp(body: MapSilpToBlpConoscInformaticaRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioConoscenzaInformaticaResponse>>;
    public insertConoscenzaInformaticaFromSilp(body: MapSilpToBlpConoscInformaticaRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioConoscenzaInformaticaResponse>>;
    public insertConoscenzaInformaticaFromSilp(body: MapSilpToBlpConoscInformaticaRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertConoscenzaInformaticaFromSilp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DettaglioConoscenzaInformaticaResponse>(`${this.basePath}/api/v1/map-silp-to-blp/insert-conoscenza-informatica`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce l&#x27;esperienza lavorativa inserito
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertEsperienzaLavFromSilp(body: MapSilpToBlpEsperienzaLavRequest, observe?: 'body', reportProgress?: boolean): Observable<DettaglioEsperienzaDiLavoroResponse>;
    public insertEsperienzaLavFromSilp(body: MapSilpToBlpEsperienzaLavRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioEsperienzaDiLavoroResponse>>;
    public insertEsperienzaLavFromSilp(body: MapSilpToBlpEsperienzaLavRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioEsperienzaDiLavoroResponse>>;
    public insertEsperienzaLavFromSilp(body: MapSilpToBlpEsperienzaLavRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertEsperienzaLavFromSilp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DettaglioEsperienzaDiLavoroResponse>(`${this.basePath}/api/v1/map-silp-to-blp/insert-esperienza-lav`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce la formazione inserita
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertFormazioneFromSilp(body: MapSilpToBlpFormazioneRequest, observe?: 'body', reportProgress?: boolean): Observable<DettaglioCorsoFormazioneBlpResponse>;
    public insertFormazioneFromSilp(body: MapSilpToBlpFormazioneRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioCorsoFormazioneBlpResponse>>;
    public insertFormazioneFromSilp(body: MapSilpToBlpFormazioneRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioCorsoFormazioneBlpResponse>>;
    public insertFormazioneFromSilp(body: MapSilpToBlpFormazioneRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertFormazioneFromSilp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DettaglioCorsoFormazioneBlpResponse>(`${this.basePath}/api/v1/map-silp-to-blp/insert-formazione`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce l&#x27;istruzione dichiarata inserita
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertIstruzioneFromSilp(body: MapSilpToBlpIstruzioneRequest, observe?: 'body', reportProgress?: boolean): Observable<DettaglioIstruzioneDichResponse>;
    public insertIstruzioneFromSilp(body: MapSilpToBlpIstruzioneRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioIstruzioneDichResponse>>;
    public insertIstruzioneFromSilp(body: MapSilpToBlpIstruzioneRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioIstruzioneDichResponse>>;
    public insertIstruzioneFromSilp(body: MapSilpToBlpIstruzioneRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertIstruzioneFromSilp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DettaglioIstruzioneDichResponse>(`${this.basePath}/api/v1/map-silp-to-blp/insert-istruzione`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce la lingua dichiarata inserita
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertLinguaDichFromSilp(body: MapSilpToBlpLinguaRequest, observe?: 'body', reportProgress?: boolean): Observable<DettaglioLinguaConosciutaResponse>;
    public insertLinguaDichFromSilp(body: MapSilpToBlpLinguaRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioLinguaConosciutaResponse>>;
    public insertLinguaDichFromSilp(body: MapSilpToBlpLinguaRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioLinguaConosciutaResponse>>;
    public insertLinguaDichFromSilp(body: MapSilpToBlpLinguaRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertLinguaDichFromSilp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DettaglioLinguaConosciutaResponse>(`${this.basePath}/api/v1/map-silp-to-blp/insert-lingua`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce la patente inserita
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertPatenteFromSilp(body: MapSilpToBlpPatenteRequest, observe?: 'body', reportProgress?: boolean): Observable<DettaglioPatentePossedutaResponse>;
    public insertPatenteFromSilp(body: MapSilpToBlpPatenteRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioPatentePossedutaResponse>>;
    public insertPatenteFromSilp(body: MapSilpToBlpPatenteRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioPatentePossedutaResponse>>;
    public insertPatenteFromSilp(body: MapSilpToBlpPatenteRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertPatenteFromSilp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DettaglioPatentePossedutaResponse>(`${this.basePath}/api/v1/map-silp-to-blp/insert-patente`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce il patentino inserito
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertPatentinoFromSilp(body: MapSilpToBlpPatenteRequest, observe?: 'body', reportProgress?: boolean): Observable<DettaglioPatentinoPossedutoResponse>;
    public insertPatentinoFromSilp(body: MapSilpToBlpPatenteRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DettaglioPatentinoPossedutoResponse>>;
    public insertPatentinoFromSilp(body: MapSilpToBlpPatenteRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DettaglioPatentinoPossedutoResponse>>;
    public insertPatentinoFromSilp(body: MapSilpToBlpPatenteRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertPatentinoFromSilp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DettaglioPatentinoPossedutoResponse>(`${this.basePath}/api/v1/map-silp-to-blp/insert-patentino`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}

