/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { NotificaResponse } from '../model/notificaResponse';
import { RicercaNotificheResponse } from '../model/ricercaNotificheResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})

export class NotifichePslpService {


    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Aggiorna la notifica se eliminata o solamente letta da silp
     * 
     * @param idSilwebNotiWeb 
     * @param operazioneDaEseguire 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public aggiornaNotifica(idSilwebNotiWeb: number, operazioneDaEseguire?: string, observe?: 'body', reportProgress?: boolean): Observable<NotificaResponse>;
    public aggiornaNotifica(idSilwebNotiWeb: number, operazioneDaEseguire?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NotificaResponse>>;
    public aggiornaNotifica(idSilwebNotiWeb: number, operazioneDaEseguire?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NotificaResponse>>;
    public aggiornaNotifica(idSilwebNotiWeb: number, operazioneDaEseguire?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSilwebNotiWeb === null || idSilwebNotiWeb === undefined) {
            throw new Error('Required parameter idSilwebNotiWeb was null or undefined when calling aggiornaNotifica.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idSilwebNotiWeb !== undefined && idSilwebNotiWeb !== null) {
            queryParameters = queryParameters.set('idSilwebNotiWeb', <any>idSilwebNotiWeb);
        }
        if (operazioneDaEseguire !== undefined && operazioneDaEseguire !== null) {
            queryParameters = queryParameters.set('operazioneDaEseguire', <any>operazioneDaEseguire);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<NotificaResponse>(`${this.basePath}/api/v1/notifiche-pslp/aggiornaNotifica`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce il numero delle notifiche e alcune notifiche da silp
     * 
     * @param idSilLavAnagrafica 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public notifichePullNotify(idSilLavAnagrafica: number, observe?: 'body', reportProgress?: boolean): Observable<RicercaNotificheResponse>;
    public notifichePullNotify(idSilLavAnagrafica: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RicercaNotificheResponse>>;
    public notifichePullNotify(idSilLavAnagrafica: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RicercaNotificheResponse>>;
    public notifichePullNotify(idSilLavAnagrafica: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSilLavAnagrafica === null || idSilLavAnagrafica === undefined) {
            throw new Error('Required parameter idSilLavAnagrafica was null or undefined when calling notifichePullNotify.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<RicercaNotificheResponse>(`${this.basePath}/api/v1/notifiche-pslp/pullNotify/${encodeURIComponent(String(idSilLavAnagrafica))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce le notifiche da silp
     * 
     * @param idSilLavAnagrafica 
     * @param page 
     * @param stato 
     * @param recForPage 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public notificheRicerca(idSilLavAnagrafica: number, page: number, stato?: string, recForPage?: number, observe?: 'body', reportProgress?: boolean): Observable<RicercaNotificheResponse>;
    public notificheRicerca(idSilLavAnagrafica: number, page: number, stato?: string, recForPage?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RicercaNotificheResponse>>;
    public notificheRicerca(idSilLavAnagrafica: number, page: number, stato?: string, recForPage?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RicercaNotificheResponse>>;
    public notificheRicerca(idSilLavAnagrafica: number, page: number, stato?: string, recForPage?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSilLavAnagrafica === null || idSilLavAnagrafica === undefined) {
            throw new Error('Required parameter idSilLavAnagrafica was null or undefined when calling notificheRicerca.');
        }

        if (page === null || page === undefined) {
            throw new Error('Required parameter page was null or undefined when calling notificheRicerca.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idSilLavAnagrafica !== undefined && idSilLavAnagrafica !== null) {
            queryParameters = queryParameters.set('idSilLavAnagrafica', <any>idSilLavAnagrafica);
        }
        if (stato !== undefined && stato !== null) {
            queryParameters = queryParameters.set('stato', <any>stato);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (recForPage !== undefined && recForPage !== null) {
            queryParameters = queryParameters.set('recForPage', <any>recForPage);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<RicercaNotificheResponse>(`${this.basePath}/api/v1/notifiche-pslp/ricercaNotifiche`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}

