/*
 * ========================LICENSE_START=================================
 * Copyright (C) 2025 Regione Piemonte
 * SPDX-FileCopyrightText: Copyright 2025 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AnagraficaLavSilpapiResponse } from '../model/anagraficaLavSilpapiResponse';
import { ApiError } from '../model/apiError';
import { Utente } from '../model/utente';
import { UtenteRequest } from '../model/utenteRequest';
import { UtenteResponse } from '../model/utenteResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})

export class UtenteService {


    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Restituisce l&#x27;utente trovato su silp passando come parametro il CF ed un boolean se è minorenne
     * 
     * @param cf 
     * @param isMinorenne 
     * @param forDelega 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cercaCFSilp(cf: string, isMinorenne: boolean, forDelega: boolean, observe?: 'body', reportProgress?: boolean): Observable<AnagraficaLavSilpapiResponse>;
    public cercaCFSilp(cf: string, isMinorenne: boolean, forDelega: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AnagraficaLavSilpapiResponse>>;
    public cercaCFSilp(cf: string, isMinorenne: boolean, forDelega: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AnagraficaLavSilpapiResponse>>;
    public cercaCFSilp(cf: string, isMinorenne: boolean, forDelega: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cf === null || cf === undefined) {
            throw new Error('Required parameter cf was null or undefined when calling cercaCFSilp.');
        }

        if (isMinorenne === null || isMinorenne === undefined) {
            throw new Error('Required parameter isMinorenne was null or undefined when calling cercaCFSilp.');
        }

        if (forDelega === null || forDelega === undefined) {
            throw new Error('Required parameter forDelega was null or undefined when calling cercaCFSilp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AnagraficaLavSilpapiResponse>(`${this.basePath}/api/v1/utente/cerca-cf-silp/${encodeURIComponent(String(cf))}/${encodeURIComponent(String(isMinorenne))}/${encodeURIComponent(String(forDelega))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce dati nuovo utente (non presente ne su SILP ne su MLPS)
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertUtente(body?: UtenteRequest, observe?: 'body', reportProgress?: boolean): Observable<UtenteResponse>;
    public insertUtente(body?: UtenteRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UtenteResponse>>;
    public insertUtente(body?: UtenteRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UtenteResponse>>;
    public insertUtente(body?: UtenteRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<UtenteResponse>(`${this.basePath}/api/v1/utente/insert-utente`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce l&#x27;utente per l&#x27;operatore
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public self(observe?: 'body', reportProgress?: boolean): Observable<Utente>;
    public self(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Utente>>;
    public self(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Utente>>;
    public self(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Utente>(`${this.basePath}/api/v1/utente/self`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restituisce l&#x27;utente passando il codice fiscale come parametro
     * 
     * @param codiceFiscale 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public utenteByCodiceFiscale(codiceFiscale: string, observe?: 'body', reportProgress?: boolean): Observable<UtenteResponse>;
    public utenteByCodiceFiscale(codiceFiscale: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UtenteResponse>>;
    public utenteByCodiceFiscale(codiceFiscale: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UtenteResponse>>;
    public utenteByCodiceFiscale(codiceFiscale: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (codiceFiscale === null || codiceFiscale === undefined) {
            throw new Error('Required parameter codiceFiscale was null or undefined when calling utenteByCodiceFiscale.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<UtenteResponse>(`${this.basePath}/api/v1/utente/utente-by-codice-fiscale/${encodeURIComponent(String(codiceFiscale))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}

